import os

MODIFIER_NAME = "to_glory_display"

output_file_frames = "o_frames.txt"
output_file_cl = "o_customizable_loc.txt"
output_file_loc = "o_localization.txt"

with open(output_file_frames, "w") as file:
    file.write(f"    # Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    for val in range(100, -1, -1):
        if val == 0:
            file.write(f"    frame = {{\n"
                       f"        number = {val}\n"
                       f"        trigger = {{ }}\n"
                       f"    }}\n")
        else:
            file.write(f"    frame = {{\n"
                       f"        number = {val}\n"
                       f"        trigger = {{ check_variable = {{ which = {MODIFIER_NAME} value = {val} }} }}\n"
                       f"    }}\n")

FLAG_NAME = "to_triumph_war_timer"
TOTAL_MONTHS = 24

with open(output_file_loc, "w") as file_loc:
    file_loc.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")

    with open(output_file_cl, "w") as file:
        bt = "\t"
        file.write(f"    # Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
        for month in range(1, TOTAL_MONTHS + 1):
            passed_days = round((TOTAL_MONTHS - month) * 30.42)

            file.write(f"{bt}text = {{\n"
                       f"{bt}\tlocalisation_key = to_{month}_tt\n")
            if month != TOTAL_MONTHS:
                file.write(f"{bt}\ttrigger = {{\n"
                           f"{bt}\t\tFROM = {{ had_country_flag = {{ flag = {FLAG_NAME} days = {passed_days} }} }}\n"
                           f"{bt}\t}}\n")
            file.write(f"{bt}}}\n")

            if month == 1:
                file_loc.write(f" to_{month}_tt:0 \"{month}\"\n")
            else:
                file_loc.write(f" to_{month}_tt:0 \"{month}\"\n")