l_english:
 SHQ:0 "Shqipëri"
 SHQ_ADJ:0 "Albanian"
 ELG_ideas:0 "Greek Ideas"
 ELG_ideas_start:0 "Greek Traditions"
 ELG_ideas_bonus:0 "Greek Ambitions"
 SHQ_ideas:0 "Albanian Ideas"
 SHQ_ideas_start:0 "Albanian Traditions"
 SHQ_ideas_bonus:0 "Albanian Ambitions"
 shqiperi:0 "Shqipëri"
 ctm_choose_own_ruler_tt:0 "A member of your own dynasty becomes the Droungarios.\n Minimum Administrative skill: §G1§!\n Minimum Diplomatic skill: §G1§!\n Minimum Military skill: §G1§!\n Average age: §G-10§!"
 ctm_choose_adm_ruler_tt:0 "A member of §YDynatoi§! becomes the Droungarios.\n Minimum Administrative skill: §G1§!\n Maximum Diplomatic skill: §R3§!"
 ctm_choose_dip_ruler_tt:0 "A member of §YPatrikioi§! becomes the Droungarios.\n Minimum Diplomatic skill: §G1§!\n Maximum Military skill: §R3§!"
 ctm_choose_mil_ruler_tt:0 "A member of §YKretan Admiralty§! becomes the Droungarios.\n Minimum Military skill: §G1§!\n Maximum Administrative skill: §R3§!"
 
 ctm_choose_own_ruler_r_tt:0 "A member of the previous ruler dynasty becomes the Megas Doux.\n Minimum Administrative skill: §G1§!\n Minimum Diplomatic skill: §G1§!\n Minimum Military skill: §R1§!\n Maximum age: §R+10§!"
 ctm_choose_adm_ruler_r_tt:0 "A member of §YDynatoi§! becomes the Megas Doux.\n Minimum Administrative skill: §G1§!\n Maximum Diplomatic skill: §R3§!"
 ctm_choose_dip_ruler_r_tt:0 "A member of §YPatrikioi§! becomes the Megas Doux.\n Minimum Diplomatic skill: §G1§!\n Maximum Military skill: §R3§!\n Average age: §G-10§!"
 ctm_choose_mil_ruler_r_tt:0 "A member of §YKretan Admiralty§! becomes the Megas Doux.\n Minimum Military skill: §G1§!\n Maximum Administrative skill: §R3§!"
 ctmElectedCand_dynatoi:0 "Dynatoi"
 ctmElectedCand_patrikoi:0 "Patrikioi"
 ctmElectedCand_admiralty:0 "Admiralty"
 
 oth_ctm_events.1.t:0 "Electing a Droungarios"
 oth_ctm_events.1.da:0 "The Megas Doux must select a successor. Each of the factions has proposed their own candidate, and the [Root.ctmElectedCand]'s choice is backed by the council. If the Megas Doux prefers, he may select a relative to take his place instead or choose any of the other factions' candidates, but the council and the people will most likely be displeased with this authoritarian choice."
 oth_ctm_events.1.db:0 "The Megas Doux must select a successor. Each of the factions has proposed their own candidate, and the [Root.ctmElectedCand]'s choice is backed by the council. If the Megas Doux prefers, he may select any of the other factions' candidates, but the council and the people will most likely be displeased with this authoritarian choice."
 oth_ctm_events.1.dc:0 "The Megas Doux must select a successor. Each of the factions has proposed their own candidate, but in the end the council couldn't come to a conclusion on who to back and thus elected to support a member of [Root.Monarch.GetName] dynasty as the most neutral choice. If the Megas Doux prefers, he may still choose any of the other factions' candidates, but the council and the people will most likely be displeased with this authoritarian choice."
 oth_ctm_events.1.a:0 "Choose a capable relative"
 oth_ctm_events.1.b:0 "Choose the Dynatoi candidate"
 oth_ctm_events.1.c:0 "Choose the Patrikioi candidate"
 oth_ctm_events.1.e:0 "Choose the Admiralty candidate"
 oth_ctm_events.1.be:0 "Choose a candidate elected by the council (§RDynatoi§!)"
 oth_ctm_events.1.ce:0 "Choose a candidate elected by the council (§lPatrikioi§!)"
 oth_ctm_events.1.ee:0 "Choose a candidate elected by the council (§TAdmiralty§!)"
 
 oth_ctm_events.2.t:0 "The Next Megas Doux"
 oth_ctm_events.2.da:0 "The Megas Doux has perished without an heir, and the factions are scrambling to select their next leader. The relatives of the previous Megas Doux are present and have put forward a candidate as well, but he didn't have much success among the scramble for power that ensured."
 oth_ctm_events.2.db:0 "The Megas Doux has perished without an heir, and the factions are scrambling to select their next leader."
 oth_ctm_events.2.dc:0 "The Megas Doux has perished without an heir, and as the factions scrambled to select their next leader, the relatives of the previous Megas Doux put forward a candidate, who seem to have struck a tune with the council and became the favourite for the next Megas Doux."
 oth_ctm_events.2.a:0 "A relative of previous Megas Doux is chosen"
 oth_ctm_events.2.be:0 "Dynatoi candidate is chosen"
 oth_ctm_events.2.ce:0 "Patrikioi candidate is chosen"
 oth_ctm_events.2.ee:0 "Admiralty candidate is chosen"
 
 ctm_dynatoi:0 "Dynatoi"
 ctm_dynatoi_FACTION_DESC:0 "Representing members of the traditional nobility who staked their claim on the limited plots of land outside the influence of major cities, the Landed Nobility seek to maintain control over the agricultural and industrial wealth of the state."
 ctm_dynatoi_influence:0 "Dynatoi Influence"
 
 ctm_patrikioi:0 "Patrikioi"
 ctm_patrikioi_FACTION_DESC:0 "Representing unlanded members of the nobility who formed trading guilds to maintain their position in society, members of the Merchant Nobility seek to control the flow of goods to and from the capital."
 ctm_patrikioi_influence:0 "Patrikioi Influence"
 
 ctm_admiralty:0 "Admiralty"
 ctm_admiralty_FACTION_DESC:0 "Representing high ranking naval officers and their men, members of the Kretan Admiralty seek to expand the size of the Kretan navy and protect against foreign invasion."
 ctm_admiralty_influence:0 "Admiralty Influence"
 
 
 