l_english:
 elysian_hellenic:0 "Elysian Pantheon"
 elysian_hellenic_religion_desc:0 " "

 elysian_religions:0 "Elysian"

 nhs_hellenic_zeus:0 "Zeus"
 nhs_hellenic_zeus_desc:0 ""

 nhs_hellenic_hera:0 "Hera"
 nhs_hellenic_hera_desc:0 ""

 nhs_hellenic_poseidon:0 "Poseidon"
 nhs_hellenic_poseidon_desc:0 ""

 nhs_hellenic_athena:0 "Athena"
 nhs_hellenic_athena_desc:0 ""

 nhs_hellenic_ares:0 "Ares"
 nhs_hellenic_ares_desc:0 ""

 nhs_hellenic_hermes:0 "Hermes"
 nhs_hellenic_hermes_desc:0 ""

 nhs_hellenic_aphrodite:0 "Aphrodite"
 nhs_hellenic_aphrodite_desc:0 ""

 nhs_hellenic_reformed_poseidon:0 "Poseidon"
 nhs_hellenic_reformed_poseidon_desc:0 ""

 nhs_hellenic_reformed_amphitrite:0 "Amphitrite"
 nhs_hellenic_reformed_amphitrite_desc:0 ""

 nhs_hellenic_reformed_oceanus:0 "Oceanus"
 nhs_hellenic_reformed_oceanus_desc:0 ""

 nhs_hellenic_reformed_atlas:0 "Atlas"
 nhs_hellenic_reformed_atlas_desc:0 ""

 nhs_hellenic_reformed_aphrodite:0 "Aphrodite"
 nhs_hellenic_reformed_aphrodite_desc:0 ""

 nhs_hellenic_reformed_orion:0 "Orion" 
 nhs_hellenic_reformed_orion_desc:0 "" 

 nhs_hellenic_reformed_triton:0 "Triton"
 nhs_hellenic_reformed_triton_desc:0 ""

 nhs_hellenic_reformed_zeus:0 "Zeus"
 nhs_hellenic_reformed_zeus_desc:0 ""

 nhs_hellenic_reformed_hera:0 "Hera"
 nhs_hellenic_reformed_hera_desc:0 ""

 nhs_hellenic_reformed_demeter:0 "Demeter"
 nhs_hellenic_reformed_demeter_desc:0 ""

 nhs_hellenic_reformed_hermes:0 "Hermes"
 nhs_hellenic_reformed_hermes_desc:0 ""

 nhs_hellenic_reformed_athena:0 "Athena"
 nhs_hellenic_reformed_athena_desc:0 ""

 nhs_hellenic_reformed_heracles:0 "Heracles"
 nhs_hellenic_reformed_heracles_desc:0 ""

 nhs_hellenic_reformed_hephasteus:0 "Hephasteus"
 nhs_hellenic_reformed_hephasteus_desc:0 ""

 nhs_hellenic_reformed_apollo:0 "Apollo"
 nhs_hellenic_reformed_apollo_desc:0 ""

 nhs_hellenic_reformed_artemis:0 "Artemis"
 nhs_hellenic_reformed_artemis_desc:0 ""

 nhs_hellenic_reformed_dionysus:0 "Dionysus"
 nhs_hellenic_reformed_dionysus_desc:0 ""

 nhs_hellenic_reformed_leto:0 "Leto"
 nhs_hellenic_reformed_leto_desc:0 ""

 nhs_hellenic_reformed_orpheus:0 "Orpheus"
 nhs_hellenic_reformed_orpheus_desc:0 ""

 nhs_hellenic_reformed_chiron:0 "Chiron"
 nhs_hellenic_reformed_chiron_desc:0 ""

 nhs_hellenic_reformed_perseus:0 "Perseus"
 nhs_hellenic_reformed_perseus_desc:0 ""