l_english:
 Elysian_Fields:0 "Elysian Fields - Andreas Waldetoft"
 Phos_Hilaron_War:0 "Phos Hilaron - Geoff Knorr"
 Phos_Hilaron_Peace:0 "Phos Hilaron - Geoff Knorr"
 Monogenes_Pais:0 "Monogenes Pais - Sean and Dean Kiner"
 Incarnation:0 "Incarnation - Sean and Dean Kiner"
 Legions_of_Rome:0 "Legions of Rome - Andreas Waldetoft"
 Epitaph_to_Seikilos_War:0 "Epitaph to Seikilos - Geoff Knorr"
 Epitaph_to_Seikilos_Peace:0 "Epitaph to Seikilos - Geoff Knorr"
 Vineyards:0 "Vineyards - Richard Beddow"
 Foederati:0 "Foederati - Richard Beddow"
 Blod_ok_Dyrd:0 "Blod ok Dyrd - Adrian von Ziegler"
 Einherjer:0 "Einherjer - Adrian von Ziegler"
 Fehu:0 "Fehu - Wardruna"
 Helvegen:0 "Helvegen - Wardruna"
 Otrothinn:0 "Otrothinn - Adrian von Ziegler"
 SS3Boss:0 "Wierd Sounds from a Distand Land"
 Crusaders_of_the_Light_Globus:0 "Crusaders of Light - Globus"
 Viking_Pagan_Folk_Song_Yggdrasill:0 "Yggdrasill - Viking Pagan Folk Song"
 Faun_Unda:0 "Unda - Faun"
 Ancient_Byzantine_Music_Byzantium:0 "Ancient Byzantine Music - Byzantium"
 War_Music_byCEPHEI_Epic_music_empire:0 "War Music - CEPHEI"