l_english:
 Hermes:0 "Hermes"
 Hermes_desc:0 "Hermes is the son of Zeus and is seen as the protector of commerce, travellers, thieves and athletes. Our merchants are inspired to travel further and make better deals; safe in the knowledge that they are being watched over by the Messenger of the Gods."
 hera:0 "Hera"
 hera_desc:0 "Hera is the Queen of Heaven, commonly associated with marriage and childbirth. Her patronage inspires fidelity among the ruling class and as such ensures their continued legitimacy in the eyes of the people."
 Aphrodite:0 "Aphrodite"
 Aphrodite_desc:0 "Aphrodite is the goddess of love, beauty, fertility and prosperity. Just as Aphrodite uses her powers to ensnare the minds of mortals, those who follow her use their charm and guile to persuade foreigners of our might and majesty."
 hellenic_festivaltz:0 "1 £dip  or 1 £mil  ruler skill after two years"
 hellenic_festivalth:0 "1 £adm  or 1 £dip  or 1 £mil  ruler skill after two years"
 hellenic_festivalta:0 "1 £mil  ruler skill after two years"
 hellenic_festivaltat:0 "1 £adm  or 1 £mil  ruler skill after two years"
 hellenic_festivalthe:0 "1 £adm  ruler skill after two years"
 hellenic_festivaltap:0 "1 £dip  ruler skill after two years"
 hellenic_festivaltp:0 "1 £dip  ruler skill after two years"
 hellenic_festivalther:0 "1 £adm  or 1 £dip  ruler skill after two years"
 
 # Greek ones temporary
 offer_to_Zeus:0 "Zeus Pleased"
 desc_offer_to_Zeus:0 "The priests tell that Zeus is pleased, this will surely secure a prosperous future for us all."
 offer_to_Poseidon:0 "Poseidon Pleased"
 desc_offer_to_Poseidon:0 "The priests tell that Poseidon is pleased, this will surely secure a prosperous future for us all."
 offer_to_Hades:0 "Hades Pleased"
 desc_offer_to_Hades:0 "The priests tell that Hades is pleased, this will surely secure a prosperous future for us all."
 offer_to_Ares:0 "Ares Pleased"
 desc_offer_to_Ares:0 "The priests tell that Ares is pleased, this will surely secure a prosperous future for us all."
 offer_to_Athena:0 "Athena Pleased"
 desc_offer_to_Athena:0 "The priests tell that Athena is pleased, this will surely secure a prosperous future for us all."
 offer_to_Hermes:0 "Hermes Pleased"
 desc_offer_to_Hermes:0 "The priests tell that Hermes is pleased, this will surely secure a prosperous future for us all."
 offer_to_Aphrodite:0 "Aphrodite Pleased"
 desc_offer_to_Aphrodite:0 "The priests tell that Aphrodite is pleased, this will surely secure a prosperous future for us all."
 offer_to_hera:0 "Hera Pleased"
 desc_offer_to_hera:0 "The priests tell that Hera is pleased, this will surely secure a prosperous future for us all."
 ####################################
 improving_ability:0 "Focus on Religion"
 desc_improving_ability:0 "The ruler is busy contemplating religious matters, and has little time dealing with mundane affairs."
 improved_ability:0 "Divine Inspiration"
 desc_improved_ability:0 "The ruler has been inspired by gods and attained improvements on ruling skills."
 cynical_believer:0 "Cynical Ruler"
 desc_cynical_believer:0 "The ruler is slowly losing support of the people due to being cynical and questioning our faith"
 hellenic_crisis:0 "Hellenic Crisis"
 desc_hellenic_crisis:0 "We may have pled to the gods for forgiveness but it seems it will take some time to actually convince the people"
 impious_believer:0 "Impious Ruler"
 desc_impious_believer:0 "The ruler is losing support of the people due to being impious to our faith, but that means it won't matter if we cut our priest budget a little more."
 # Greek ones temporary
 hellenic_events.101.t:0 "Hetairideia"
 hellenic_events.101.d:0 "It is Hetairideia, a festival dedicated to our supreme god of sky. With the statue of Zeus carried, the celebrating people paraded down the main streets of [Root.Capital.GetCapitalName]. When they finally reach the destination, a sumptuous feast is about to be held. Zeus is formally invited and his seat is arranged at the most honorable part of the table. 'Praise Zeus!' shouting and cheering the people."
 hellenic_events.101.a:0 "All glory to Zeus!"
 hellenic_events.101.b:0 "The almightiness of Zeus has given me inspirations."
 hellenic_events.102.t:0 "Inspirations of Zeus"
 hellenic_events.102.d:0 "After contemplation and learning over a long time, you feel like you have a deeper understanding of the almightiness of Zeus."
 hellenic_events.102.a:0 "It is his domination over all other gods makes Zeus almighty."
 hellenic_events.102.b:0 "It is the power of thunder makes Zeus almighty."
 hellenic_events.120.t:0 "Sounion Magno"
 hellenic_events.120.d:0 "Poseidon, the God of the Sea, Lord of Horses, and the patron god to many of our sailors, thanks to his role in the calming of the Great Storm. Our brave sailors are assembled at the square before the temple of Poseidon, waiting for the ritual of Sounion Magno to begin. The priests walk out of the temple and stand before the assembled crowd. Great cheers well up from the masses as three, single-horned bulls, representing the three prongs of Poseidon's Trident, are brought forth and drowned in Neptuno Adventus. As is custom, a ship bearing the name Neptunus Magnis is put to sea."
 hellenic_events.120.a:0 "I shall lead the procession!"
 hellenic_events.120.b:0 "Before I can truly enjoy such a festival I need to know more about the sea"
 hellenic_events.121.t:0 "Inspirations of Poseidon"
 hellenic_events.121.d:0 "You spend last few months in the company of sailors and shipwrights, learning about the secrets of the ocean, domain of Poseidon."
 hellenic_events.121.a:0 "It truly is fascinating!"
 hellenic_events.103.t:0 "Necromanteion"
 hellenic_events.103.d:0 "The Necromanteion begins today, a week-long festival that honours Hades, the God of the dead and all things found beneath the earth. What seems to be all of the men and women in [Root.Capital.GetCapitalName] have gathered near the temple of Hades early this morning. They wish to speak to the dead, and were served a meal of broad beans, pork, barley bread and oysters. Following a cleansing ceremony and the sacrifice of a black sheep, the heads of each family descend through to an underground temple and leave offerings of gold and silver as they pass through a series of thirteen iron gates. As they pass through the final gate, an oracle awaits for them, surrounded in thick smoke, to help them transition to a state in which they could contact their ancestors."
 hellenic_events.103.a:0 "Honour the Ancestors"
 hellenic_events.103.b:0 "I must learn from my Ancestors!"
 hellenic_events.104.t:0 "Ancestors' Advice"
 hellenic_events.104.d:0 "You discussed with oracles about the visions you saw when you were brought before the gate of Hades. You are now aware of your ancestors' mistakes and shortcomings, vowing to heed their advice and not make the same mistakes as they did."
 hellenic_events.104.a:0 "It is clear that we should focus on domestic affairs."
 hellenic_events.104.b:0 "It was our lack of outside reach that dragged us down."
 hellenic_events.104.c:0 "They were weak and I shall not make the same mistake!"
 hellenic_events.105.t:0 "Sacrifice to Ares"
 hellenic_events.105.d:0 "Our brave soldiers are assembled at the square before the temple of Ares, waiting for the ritual to begin. The priests walk out of the temple and stand before the altar. The Sacrifice to Ares begins, sacrifices are made, trumpets are sounded. Soldiers and their weapons and armours are purified. This marks the end of last summer campaign season until the new one begins the next spring."
 hellenic_events.105.a:0 "A glorious procession will be held."
 hellenic_events.105.b:0 "I'm curious why a festival about peace is held in honour of Ares, the god of war."
 hellenic_events.106.t:0 "Inspirations of Ares"
 hellenic_events.106.d:0 "You spent a long time contemplating and learning, yet still feel clueless about the secret of the festival of Sacrifice to Ares."
 hellenic_events.106.a:0 "At least we should not attack the enemy in winter."
 hellenic_events.107.t:0 "Plynteria"
 hellenic_events.107.d:0 "Plynteria, the festival dedicated to Athena, our virgin goddess of wisdom, begins today. It is celebrated not only by those who worship her as their patron deity, such as scholars, doctors, and artisans. It is a festival enjoyed by everyone. New plays choose to debut on this day, and theatres are full of people early in the morning. Contests of oration and poetry are held before the temple of Athena, winners are crowned with a laurel wreath. The celebration will last for five days."
 hellenic_events.107.a:0 "Wisdom is power!"
 hellenic_events.107.b:0 "Which one is more important for a good monarch, wisdom or force?"
 hellenic_events.108.t:0 "Inspirations of Athena"
 hellenic_events.108.d:0 "You have been thinking about the way of being a good ruler for a long time, and feel like you have found your answer."
 hellenic_events.108.a:0 "A good ruler always use [Root.Monarch.GetHerHis] wisdom."
 hellenic_events.108.b:0 "A good ruler knows when to use the force."
 hellenic_events.109.t:0 "Hermaia"
 hellenic_events.109.d:0 "'All those who make a living trading their wares, offer you incense, and beg you to swell their profits.' thus wrote Ovid. Hermaia, a festival dedicated to Hermes begins. Merchants from all over the city and from near areas have all gathered before the temple of Hermes in [Root.Capital.GetCapitalName]. After offering a sacrifice to the protector of commerce, they draw water from the fountain near the temple and then sprinkle their goods and hair with a laurel bough and pray for good luck."
 hellenic_events.109.a:0 "A golden key can open any door!"
 hellenic_events.109.b:0 "Hmm, it is interesting that a god of commerce is also the protector of thieves."
 hellenic_events.110.t:0 "Inspirations of Hermes"
 hellenic_events.110.d:0 "You went to a local market recently, a place under protection of Hermes. You found traders trying to cheat their customers. 'Catch the thief!' cried a woman, you squinted in the direction of the voice and saw a boy running with a gold necklace in his hand. 'Smart boy, how could he steal a necklace when its owner is wearing it?' you asked yourself."
 hellenic_events.110.a:0 "At least trickery can make us rich!"
 hellenic_events.111.t:0 "Adonia"
 hellenic_events.111.d:0 "'Aphrodite, you changer of hearts. We shall perform your rites. May your blessing be on us.' the priestesses complete the prayer and the ritual of Adonia begins. Female attendants of the goddess, chosen from all women in [Root.Capital.GetCapitalName], undress the statue and wash it ceremonially with warm water. Once the statue is dry, fresh flowers are offered and it is garlanded with myrtle. And then the statue is carried out of her temple, the celebrating begin."
 hellenic_events.111.a:0 "Aphrodite blesses those who love her!"
 hellenic_events.111.b:0 "The grumpy are pacified, anger turned into joy. What is the secret of such power of Aphrodite?"
 hellenic_events.112.t:0 "Inspirations of Aphrodite"
 hellenic_events.112.d:0 "You talked with wise men and read ancient stories, you feel like you have found the reason. The Romans regarded Aphrodite as their divine mother and Ares as divine father, and the glory of the empire was thus built upon the combination of love and war."
 hellenic_events.112.a:0 "A wise ruler uses [Root.Monarch.GetHerHis] love wisely."
 hellenic_events.113.t:0 "Crisis of Faith"
 hellenic_events.113.d:0 "You acted cynically toward your patron god but didn't get punished, you prayed and received no reply. You feel like you have lost faith in your god while the priests told it is just a crisis of faith that everyone will experience. Maybe I have been praying to the wrong one and it is time to change?"
 hellenic_events.113.a:0 "It is a test of gods which I shall pass."
 hellenic_events.113.b:0 "Zeus is the supreme god."
 hellenic_events.113.c:0 "I follow Hades, ruler of the underworld."
 hellenic_events.113.e:0 "Ares will lead us to victory."
 hellenic_events.113.f:0 "I follow Athena in way of wisdom."
 hellenic_events.113.g:0 "We will gain our prosperity from Hermes."
 hellenic_events.113.h:0 "I worship Aphrodite, goddess of love and beauty."
 hellenic_events.122.t:0 "Daidala"
 hellenic_events.122.d:0 "The festival of Daidala begins today. Women in [Root.Capital.GetCapitalName] gathered at the temple of Hera early this morning, wearing their hair loose and leaving not a single knot in their robes. The ritual soon begins, a white lamb and a small calf are sacrificed at the altar, sanctity of marriage, birth of new lives, and peace are prayed for. At home, husbands and children are ready to shower their wives and mothers with gifts."
 hellenic_events.122.a:0 "May Hera bless us all!"
 hellenic_events.122.b:0 "The aspects of being wife, mother and queen simultaneously has given me inspirations."
 hellenic_events.123.t:0 "Inspirations of Hera"
 hellenic_events.123.d:0 "You discussed with scholars and theologians about the importance of the bonds of marriage, the harmony of family life, and the role they play in maintaining a peaceful diplomatic relationship. Now you have a better understanding of your faith."
 hellenic_events.123.a:0 "Hera revealed how can different nations unite as one."
 hellenic_events.123.b:0 "Hera revealed how to balance domestic affairs."
 hellenic_events.0.a:0 "We will unfortunately not attend the celebrating."
 hellenic_events.0.b:0 "Hah, stupid commoners."
 