l_english:

 # 00_scripted_functions.txt
 BELONGS_TO_ELG:0  "The province belongs to Konstantinia"
 HAS_NATIVE_COUNCIL:0  "Barbaroi Councils influential (over §W60§) or disloyal (below §R30§)"
 NHS_LAKES_RESTR:0  "£icon_x_font£§YOwns§! or §Ycolonial subject§! any neighbouring province."
 NHS_NO_EXPLOIT_WHILE_EMIGRATION:0  "§RCannot exploit development while the local population is emigrating.§!"
 NHS_NO_RENESSIANCE:0  "£icon_x_font£Has embraced Renaissance"
 NHS_RESTRICTED:0  "§ROur overlord has restricted us from colonising here§!"
 VINLAND_CAPITAL:0  "Capital can only be moved via a decision."
