l_english:
 
 # 01_nhs_subject_types.txt
 elysian_subject:0 "Exarchate"
 elysian_subject_is_our:0 "§Y$NAME$§! is our Exarchate."
 elysian_subject_long_desc:0 "The Exarchate is a provincial post which is provided with increased political and military authority over a particularly large and important region."
 elysian_subject_title:0 "Exarchate"
 elysian_subject_title_plural:0 "Exarchates"
 elysian_subject_non_exarch:0 "Exarchate"
 elysian_subject_non_exarch_is_our:0 "§Y$NAME$§! is our Exarchate."
 elysian_subject_non_exarch_long_desc:0 "The Exarchate is a provincial post which is provided with increased political and military authority over a particularly large and important region."
 elysian_subject_non_exarch_title:0 "Exarchate"
 elysian_subject_non_exarch_title_plural:0 "Exarchates"
 elysian_subject_varangian:0 "Kleisoura"
 elysian_subject_varangian_is_our:0 "§Y$NAME$§! is our Military Order."
 elysian_subject_varangian_long_desc:0 "The Kleisoura is a small military post focused almost entirely on fortifying a frontier region against foreign invasion, with elite soldiers garrisoning many of its towns and forts at all times."
 elysian_subject_varangian_title:0 "Kleisoura"
 elysian_subject_varangian_title_plural:0 "Kleisouras"
 nhs_imperial_associate:0 "Imperial Associate"
 nhs_imperial_associate_title:0 "Imperial Associate"
 nhs_imperial_associate_is_our:0 "§Y$NAME$§! is our Imperial Associate."
 nhs_imperial_associate_long_desc:0 ""
 nhs_imperial_associate_title_plural:0 "Imperial Associates"
 nhs_protectorate:0 "Imperial Protectorate"
 nhs_protectorate_title:0 "Imperial Protectorate"
 nhs_protectorate_is_our:0 "§Y$NAME$§! is our Protectorate."
 nhs_protectorate_long_desc:0 "A Imperial Protectorate will provide half of its trade power to the overlord, while the overlord protects it."
 nhs_protectorate_title_plural:0 "Imperial Protectorates"
 