l_english:
 
 # 00_default.txt
 ab_to_intercontinental_trade:0 "Intercontinental Trade"
 obj_to_colonial_empire_na:0 "Create a Colonial Empire"
 obj_to_colonial_empire_sa:0 "Create a Colonial Empire"
 obj_to_control_trade:0 "Control Trade"
 obj_to_cultural_resurgence:0 "Cultural Resurgence"
 obj_to_modernize:0 "Ahead of Time"
 obj_to_one_path_ends_green:0 "One Path Ends"
 obj_to_one_path_ends_purple:0 "One Path Ends"
 obj_to_revered_court:0 "Magnificent Court"
 obj_to_revered_court_devotion:0 "Paragon of Virtue"
 obj_to_revered_court_horde_unity:0 "Unified Horde"
 obj_to_revered_court_rep_tradition:0 "Model Republic"
 obj_to_well_advised:0 "Well Advised"
 to_owns_atlantic_port_tt:0 "Owns an §YAtlantic§! port"
 