l_english:
 nhs_HighTierBuildingCount:0 "A New Homeland Mission Progress"
 nhs_HomelandsBuildingCount:0 "Infrastructure Projects Mission Progress"
 to_ElysiumBuildingCount:0 "A New Homeland Mission Progress"