l_english:
 EST_CRUSHED_APOGONOI:0 "The Apogonoi have been curtailed"
 EST_CRUSHED_NHS_NOBLES:0 "The Nobles have been curtailed"
 EST_CRUSHED_PIPILTIN:0 "The Pipiltin have been curtailed"
 elysian_revolution:0 "Elysian Revolution"
 estate_all_natives_disaster:0 "Native Independence"
 estate_all_natives_disaster_desc:0 "The Native Councils have grown so powerful that they have broken off to form a country of their own, outside of our control."
 estate_nhs_apogonoi_disaster:0 "Rise of the Apogonoi"
 estate_nhs_apogonoi_disaster_desc:0 "The Apogonoi have grown so powerful, they have assumed de facto control over our country."
 estate_nhs_nobility_disaster:0 "Rise of the Dynatoi"
 estate_nhs_nobility_disaster_desc:0 "The Dynatoi have grown so powerful, they have assumed de facto control over our country."
 estate_nhs_pipiltin_disaster:0 "Rise of the Pipiltin"
 estate_nhs_pipiltin_disaster_desc:0 "The Pipiltin have grown so powerful, they have assumed de facto control over our country."
 infighting_active_for_5_years_tooltip:0 "Disaster has been active for 5 years."
 nhs_elysian_revolution_scythian_revolt_end_appeasement_tt:0 "Compromise has been reached with §YSkythian Separtists§!."
 nhs_elysian_revolution_scythian_revolt_end_tt:0 "§YSkythian Separtists§! have been defeated and they controll none of their core provinces."
 nhs_elysian_revolution_scythian_revolt_start_tt:0 "Skythians have declared their demands."
 nhs_natives_disaster_timer_tt:0 "The disaster has been active for 3 years, or terms have been negotiated"
 nhs_scythian_revolt:0 "Skythian Revolt"
 republican_infighting:0 "The Second Elysian Civil War"
 revolution_one_side_must_win_tooltip:0 "One side must declare victory.\nCurrent progress of the revolution: §G[Root.RevolutionCountingVariable.GetValue]§!\nUpon reaching the value of §R10§! or less the revolution will be crushed.\nUpon reaching the value of §G110§! or §G80§! if we end up in a regency, the revolutionaries will proclaim victory."
 
 # 09_hellenic_revolt.txt
 nhs_hcd_hellenic_crisis:0 "Elysian Religious Wars"
 nhs_hcd_hellenic_crisis_angered_Orthodox.tt:0 "Neo-Pagans are §Oangered§!"
 nhs_hcd_hellenic_crisis_angered_Pagans.tt:0 "The Orthodox church is §Oangered§!"
 nhs_hcd_hellenic_crisis_over.tt:0 "The Neo-Pagans are no longer a threat"
 nhs_hcd_hellenic_crisis_upset_Orthodox.tt:0 "The Orthodox church is §Routraged§!"
 nhs_hcd_hellenic_crisis_upset_Pagans.tt:0 "Neo-Pagans are §Routraged§!"
 