l_english:
 
 # 00_diplomatic_actions.txt
 100_YEAR_PEACE:0 "§RTreaty of the false king is in place.§!"
 ANNEX_IA_50_YEARS:0 "You may only Annex a nation that has been your Imperial Associate for at least §Y50§! years."
 ANNEX_TOO_LOW:0 "Your subject needs to have at least §Y+190§! opinion of you for you to be able to start an annexation."
 ANNEX_TOO_LOW_KOINE_GLOSSA:0 "Your subject needs to have at least §Y+50§! opinion of you for you to be able to start an annexation."
 INTEGRATETOOLOWDESC_KOINE_GLOSSA:0 "You need at least §Y+50§! relations with a country to integrate them."
 MSG_NO_WAR_WITH_PACTMATES:0 "There's bigger fish to fry. Take down §Y[GetExistingElysiaName]§! first before contemplating betrayal."
 NHS_CANNOT_ALLY_YET:0 "Negotiations with both colonies are still going on."
 NHS_COLONIES:0 "Non-Aggression Pact"
 NHS_NATIVE_EARLY:0 "You must wait until §Y1 August 1447§! before declaring any wars on Rhomanía."
 NHS_NATIVE_EARLY_ELY:0 "Our people are still busy recovering from the voyage. We must wait until §Y1 August 1447§! before declaring any wars."
 NHS_ONLY_ONE_VIKING_ALLY:0 "We cannot ally both Viking colonies."
 NHS_ONLY_ONE_VIKING_ALLY_V:0 "Only one Viking colony can be allied to §Y[From.GetName]§!."
 NHS_ONLY_TRADING_VIKING_ALLY:0 "We can only ally the Viking colony we are trading with"
 NHS_ONLY_TRADING_VIKING_ALLY_V:0 "We can only ally §Y[From.GetName]§! if we are trading with them"
 NHS_VARANGIANS_INSULT_MASTER:0 "As a military order we simply cannot insult our overlord."
 TO_ANNEX_PROTECTORATE_20_YEARS:0 "You may only Annex a protectorate which has been your subject for at least §Y20§! years.[GetProtectorateAnnexationDate]"
 TO_ANNEX_PROTECTORATE_AFRICA:0 "Annexation of protectorates in §YAfrica§! requires the completion of §MAround Africa§! mission."
 TO_ANNEX_PROTECTORATE_EAST_ASIA:0 "Annexation of protectorates on §YEast Indies§!, §YOceania§!, §YChina§! and §YFar East§! subcontinents requires the completion of §MEast Asian Monopolies§! mission."
 TO_ANNEX_PROTECTORATE_INDIA:0 "Annexation of protectorates in §YIndia§! requires the completion of §MIndian Ambition§! mission."
 TO_ANNEX_PROTECTORATE_OPINION:0 "Your subject needs to have at least §Y+190§! opinion of you for you to be able to start an annexation."
 TO_ANNEX_PROTECTORATE_POLYNESIA_PHILIPPINES:0 "Annexation of protectorates in §YPolynesia§! and §YPhilippines§! requires the completion of §MAcross the Eirenic§! mission."
 TO_ANNEX_PROTECTORATE_WITHOUT_KOINE_GLOSSA:0 "Annexation of this protectorate requires the completion of §MKoine Glossa§! mission."
 TO_ANNEX_PROTECTORATE_WITH_KOINE_GLOSSA:0 "Your subject needs to have at least §Y+50§! opinion of you for you to be able to start an annexation."
 TO_COLONIAL_COMPETITION:0 "They will not ally us as long as we have an exclusive trade deal with §Y[GetExistingElysiaName]§!."
 TO_COLONIAL_COMPETITION_FOREIGN:0 "They will not ally us as long as they have an exclusive trade deal with §Y[GetExistingElysiaName]§!."
 TRADE_DEAL:0 "We have a trade deal."
 nhs_giftaction_but_why_tt:0 "The recipient is §Y[TUR.GetName]§!, but why would you do that?"
 to_has_repelled_elysian_deal_tt:0 "We cannot declare war on [From.GetName] as long as the Trade Agreement is active. The agreement will be annulled if we enact §YRevoke Greek Trade Privileges§! decision, or conquer one of their provinces."
 to_has_repelled_portuguese_deal_tt:0 "We cannot declare war on [From.GetName] as long as the Trade Agreement is active. The agreement will be annulled if we enact §YRepeal Portuguese Trade Agreement§! decision, or conquer one of their provinces."
 to_neighbors_allied_country_tt:0 "§Y[From.GetName]§! neighbours an ally of §Y[Root.GetName]§!."
 to_neighbors_country_tt:0 "§Y[From.GetName]§! neighbours §Y[Root.GetName]§!."
 