l_english:
 
 # TO_NAT_clans_agendas.txt
 estate_clans_annex_subject:0 "Annex [agenda_country.GetUsableName]"
 estate_clans_befriend_rival_of_rival:0 "Befriend [rival_country.GetUsableName]'s Rivals"
 estate_clans_bigger_army_than_rival:0 "Protect against [agenda_country.GetUsableName]"
 estate_clans_build_an_army:0 "Build an Army for our Tribe"
 estate_clans_build_up_manpower_reserves:0 "Build up our Manpower Reserves"
 estate_clans_complete_conquest_of_x:0 "Complete the Conquest of [agenda_province.GetAreaName]"
 estate_clans_convert_province_culture:0 "Make [agenda_province.GetName] [Root.Culture.GetName]"
 estate_clans_crush_revolts:0 "Crush the Rebels"
 estate_clans_despoil_x:0 "Despoil [agenda_province.GetAreaName]"
 estate_clans_expand_into_x:0 "Expand into [agenda_province.GetAreaName]"
 estate_clans_protect_our_culture:0 "Protect the [Root.GetAdjective] Population in [agenda_province.GetName]"
 estate_clans_regain_liberty:0 "Regain our Liberty"
 estate_clans_relations_with_X:0 "Improve Relations with [agenda_country.GetUsableName]"
 estate_clans_retake_core:0 "Retake [agenda_province.GetName]"
 estate_clans_three_privileges:0 "Extend Tribal Privileges"
 estate_clans_vassalise_vulnerable_country:0 "Vassalize [agenda_country.GetUsableName]"
 