l_english:
 
 # TO_CM1_factions.txt
 ctm_admiralty:0 "Admiralty"
 ctm_admiralty_FACTION_DESC:0 "Representing high ranking naval officers and their men, members of the Kaudan Admiralty seek to expand the size of the Kaudan navy and protect against foreign invasion."
 ctm_admiralty_influence:0 "Admiralty Influence"
 ctm_dynatoi:0 "Dynatoi"
 ctm_dynatoi_FACTION_DESC:0 "Representing members of the traditional nobility who staked their claim on the limited plots of land outside the influence of major cities, the Landed Nobility seek to maintain control over the agricultural and industrial wealth of the state."
 ctm_dynatoi_influence:0 "Dynatoi Influence"
 ctm_patrikioi:0 "Patrikioi"
 ctm_patrikioi_FACTION_DESC:0 "Representing unlanded members of the nobility who formed trading guilds to maintain their position in society, members of the Merchant Nobility seek to control the flow of goods to and from the capital."
 ctm_patrikioi_influence:0 "Patrikioi Influence"
 
 # TO_VOV_factions.txt
 vin_farmadr:0 "Farmenn Faction"
 vin_farmadr_FACTION_DESC:0 "As explorers and traders, the Farmenn established themselves has a major political power in Vinland after their important role during the first Roman contacts."
 vin_farmadr_influence:0 "Farmenn Influence"
 vin_gothar:0 "Gothar Faction"
 vin_gothar_FACTION_DESC:0 "After the Norse Reformation, the Gothar were quick to establish themselves in the Althing, hoping to aid Vinland's internal growth and promote the spread of Norsedom."
 vin_gothar_influence:0 "Gothar Influence"
 vin_vikingr_influence:0 "Vikingar Influence"
 vin_vikingr:0 "Vikingar Faction"
 vin_vikingr_FACTION_DESC:0 "Thanks to years of tradition and large accumulated wealth, the Vikingar, the norse raiders, are a big influence in Althing's politics."
 