l_english:
 
 # 00_Core.txt
 EUROPEAN_ENCLAVE:0 "§YForeign Trade Quarter§!: Institution is present in any European Atlantic coastal Center of Trade"
 LARGE_PORTUGESE_ENCLAVE:0 "§YLarge Portuguese Enclave§!: Institution is present in any of the Portuguese ports"
 NHS_ELYSIAN_INFLUENCES:0 "Roman Influences"
 PORTUGESE_ENCLAVE:0 "§YPortuguese Enclave§!: Institution is present in any of the Portuguese ports"
 SMALL_PORTUGESE_ENCLAVE:0 "§YSmall Portuguese Enclave§!: Institution is present in any of the Portuguese ports"
 TO_FREE_TRADE:0 "§YFree Trade§!: Institution is present in any European Atlantic coastal Center of Trade"
 TO_RESTRICTED_TRADE:0 "§YRestricted Trade§!: Institution is present in any European Atlantic coastal Center of Trade"
 to_books_renaissance_spread_tt:0 "Owner has §YBooks of Knowledge§! modifier and the province is capital or has at least §Y10§! development."
 to_colonialism_spread_atlantic_ports_tt:0 "Atlantic port of a §YWestern§! nation with §YQuest for the New World§! idea"
 to_colonialism_spread_capital_tt:0 "Capital of a §YWestern§! nation with an Atlantic port and §YQuest for the New World§! idea"
 to_completed_a_true_nation_mission_tt:0 "Completed Mission §YA True Nation§!"
 to_does_not_have_beacon_of_liberty_tt:0 "Has not enacted Government Reform §YBeacon of Liberty§!"
 to_enacted_modernize_decision_tt:0 "Has enacted §YModernize the Realm§! decision"
 to_interest_in_overseas_exploration_renewed_tt:0 "Interest in overseas exploration has been renewed"
 to_is_NOT_island_tt:0 "§Y[This.GetName]§! is NOT an island"
 to_nat_feudalism_spread_from_overlord_tt:0 "Overlord has embraced Legalism."
 to_nat_feudalism_spread_from_reform_tt:0 "Owner or overlord has enacted a Tier V native government reform."
 to_nat_feudalism_spread_from_romans_tt:0 "Dealings with Romans"
 to_three_months_since_magellan_departed_tt:0 "At least §Y3§! months have passed since Magellan's departure."
 