l_english:
 
 # 00_Core.txt
 EUROPEAN_ENCLAVE:0 "European Enclave"
 LARGE_PORTUGESE_ENCLAVE:0 "Large Portuguese Enclave"
 NHS_ELYSIAN_INFLUENCES:0 "Elysian Influences"
 NHS_FREE_TRADE:0 "Free Trade"
 NHS_MODERNISATION_TT:0 "Modernising"
 PORTUGESE_ENCLAVE:0 "Portuguese Enclave"
 SMALL_PORTUGESE_ENCLAVE:0 "Small Portuguese Enclave"
 nhs_books_renaissance_spread_tt:0 "Owner has §YBooks of Knowledge§! modifier and is capital or has at least 12 development."
 nhs_colonial_ambitions_tt:0 "Colonial Ambitions"
 nhs_has_completed_industrial_revolution_mission:0 "Completed Mission §YCapital of Innovation§!"
 nhs_has_nhs_europe_discovered:0 "Pytheas' great voyage completed"
 to_nat_feudalism_spread_from_overlord_tt:0 "Overlord has embraced Legalism."
 to_nat_feudalism_spread_from_reform_tt:0 "Owner or overlord has enacted a Tier V native government reform."
 