l_english:
 claimed_our_throne:0 "Claimed our Throne!"
 msg_broke_pact:0 "Broke Our Pact"
 msg_severed_ties_opinion:0 "Cut Ties with Our Nation!"
 nhs_hcd_diverted_blame:0 "Accused of Land Theft"
 nhs_hcd_heathen_state:0 "Depraved Heathens"
 to_created_lanfang:0 "Invited Kongsi Federations"
 to_deposed_ecumenical:0 "Deposed the Ecumenical Patriarch"
 to_deposed_ecumenical_low:0 "Deposed the Ecumenical Patriarch"
 to_in_confederation:0 "In Confederation"
 to_is_lanfang:0 "Our Kongsi Federations"
 to_lanfang_origin:0 "Origin"
 to_nat_diplomatic_outreach:0 "Diplomatic Outreach"
 to_nat_diplomats_denied:0 "Denied our diplomats"
 to_nat_envoy_to_the_world_opinion:0 "Envoy to the World"
 
 # TO_ELY_opinion_modifiers.txt
 denied_autocephaly:0 "Denied Autocephaly"
 is_elysian_governor:0 "Governorate"
 is_iassociate:0 "Imperial Associate"
 is_iprotectorate:0 "Protectorate"
 nhs2_expansion:0 "Stolen lands"
 nhs2_jannisaries_angry:0 "Recruiting Janissaries"
 nhs_abandoned:0 "Abandoned"
 nhs_accepted_gift:0 "Accepted gift"
 nhs_appreciates_pantheon:0 "Appreciates our Pantheon"
 nhs_been_helped_in_need:0 "Been Helped in Need"
 nhs_borderconflict_gold:0 "Border conflict over goldmine"
 nhs_broke_the_deals:0 "Broke Deals"
 nhs_constantinople_deal_op:0 "Ceded Konstantinoupolis"
 nhs_converted_orthodox:0 "Converted to Orthodox"
 nhs_deception:0 "Deception"
 nhs_deception_por:0 "Deception"
 nhs_dissapointed:0 "Disappointed"
 nhs_fears_demons:0 "Fears demon worshippers"
 nhs_first_contact_o:0 "First Contact"
 nhs_forced_culture_change:0 "Forced culture change"
 nhs_formed_greeko:0 "Formed Konstantinia"
 nhs_generous_deal:0 "Generous trade deal"
 nhs_helped_in_need:0 "Offered Help in Need"
 nhs_msg_given_help_opinion:0 "Supplies"
 nhs_msn_embraced_aztlan:0 "Embraced Aztlan"
 nhs_naphta_deal:0 "Naphtha Deal"
 nhs_natives_hw_denied_o:0 "Smoothed Relations"
 nhs_no_constantinople_deal_op:0 "Refused to cede Konstantinoupolis"
 nhs_not_converted_orthodox:0 "Refused conversion"
 nhs_o_embraced_new_religion:0 "Religion"
 nhs_por_trade_deal:0 "Trade Deal"
 nhs_recognised_patriarch_o:0 "Recognised new Patriarch"
 nhs_reduced_friction:0 "Reduced friction"
 nhs_refused_trade_deal:0 "Disappointed"
 nhs_secret_ally:0 "Grateful"
 nhs_took_patriarchate_ignored_opinion:0 "Ignored the Conquest"
 nhs_took_patriarchate_reacted_opinion:0 "Reacted"
 nhs_unchecked_expansion:0 "Free Expansion"
 nhs_upheld_trade:0 "Upheld Deals"
 nhs_worships_demons:0 "Worships Demons"
 nhs_you_done_f_up:0 "Furious"
 recognized_autocephaly:0 "Recognised Autocephaly"
 to_burned_hagia_sophia:0 "Razed Hagia Sophia"
 to_burned_hagia_sophia_severe:0 "Razed Hagia Sophia"
 to_burned_venice_neg_om:0 "The Sack of Venice"
 to_burned_venice_neg_severe_om:0 "The Sack of Venice"
 to_burned_venice_om:0 "The Sack of Venice"
 to_burned_venice_ven_om:0 "The Sack of Venice"
 to_conquered_rome_minor_om:0 "Conquered Rome"
 to_conquered_rome_minor_severe_om:0 "Conquered Rome"
 to_conquered_rome_om:0 "Conquered Rome"
 to_conquered_rome_pagan_minor_om:0 "Conquered Rome"
 to_conquered_rome_pagan_minor_severe_om:0 "Conquered Rome"
 to_conquered_rome_pagan_om:0 "Conquered Rome"
 to_conquered_rome_pagan_severe_om:0 "Conquered Rome"
 to_conquered_rome_pagan_small_om:0 "Conquered Rome"
 to_conquered_rome_pagan_small_severe_om:0 "Conquered Rome"
 to_conquered_rome_severe_om:0 "Conquered Rome"
 to_disbanded_varangian_order_om:0 "Disbanded the Varangian Order"
 to_executed_pope_minor_om:0 "Executed the Pope"
 to_executed_pope_minor_severe_om:0 "Executed the Pope"
 to_executed_pope_om:0 "Executed the Pope"
 to_executed_pope_severe_om:0 "Executed the Pope"
 to_expelled_turks:0 "Expelled Turks from Anatolia"
 to_expelled_turks_severe:0 "Expelled Turks from Anatolia"
 to_free_haven_pirate_opinion:0 "Free Haven"
 to_gave_hagia_sophia_to_greeks:0 "Defiled Hagia Sophia"
 to_gave_hagia_sophia_to_greeks_severe:0 "Defiled Hagia Sophia"
 to_kept_hre_bureaucracy_om:0 "Kept the Local Bureaucracy Intact"
 to_por_hates_colonizers:0 "Colonial Competition"
 to_raided_by_varangians_minor_om:0 "Raided by Varangians"
 to_raided_by_varangians_om:0 "Raided by Varangians"
 to_returned_rome_om:0 "Returned Rome"
 to_sacked_rome_minor_om:0 "Burned Rome"
 to_sacked_rome_minor_severe_om:0 "Burned Rome"
 to_sacked_rome_om:0 "Burned Rome"
 to_sacked_rome_severe_om:0 "Burned Rome"
 to_trade_expedition_opinion:0 "Trade Expedition"
 to_varangian_ties_om:0 "Varangian Ties"
 
 # TO_VoV_opinion_modifiers.txt
 nhs_allowed_marchants:0 "Allowed Merchants"
 nhs_broken_trade:0 "Broken Trade Deal"
 nhs_broken_trade_big:0 "Outraged"
 nhs_no_trade:0 "Refused Trade"
 nhs_send_v_home_opinion:0 "Returning Varangians"
 nhs_vov_norse_feud:0 "Norse Feud"
 nhs_vov_norse_insult:0 "Norse Insult"
 nhs_vov_other_insult:0 "Insult"
 nhs_vov_trade1:0 "Trade Deal"
 nhs_vov_trade2:0 "Trade Deal"
 