l_english:
 CB_ALLOWED_to_pt_enforce_hegemony_over_sparta:0 "Enforce Hegemony"
 PEACE_to_pt_enforce_hegemony_over_sparta:0 "§GEnforce Hegemony§!"
 to_pt_enforce_hegemony_over_sparta_desc:0 "[From.GetName] becomes a [This.GetAdjective] Imperial Associate."
 CB_ALLOWED_to_pt_establish_protectorate:0 "Establish Protectorate"
 PEACE_to_pt_establish_protectorate:0 "-§MEstablish Protectorate§!"
 to_pt_establish_protectorate_desc:0 "[From.GetName] becomes a [This.GetAdjective] Protectorate"
 CB_ALLOWED_to_pt_restore_dynasty_in_sparta:0 "Restore Dynasty"
 PEACE_to_pt_restore_dynasty_in_sparta:0 "§YRestore Dynasty§!"
 to_pt_restore_dynasty_in_sparta_desc:0 "[From.GetName] becomes a [This.GetAdjective] §YImperial Associate §!and proper §YSpartakon§! dynasty member returns on their throne."
 