l_english:
 CB_ALLOWED_to_pt_establish_protectorate:0 "Establish Protectorate"
 PEACE_to_pt_establish_protectorate:0 "-§MEstablish Protectorate§!"
 to_pt_establish_protectorate_desc:0 "[From.GetName] becomes a [This.GetName] Protectorate"
 CB_ALLOWED_to_pt_restore_dynasty:0 "Restore Dynasty"
 PEACE_to_pt_restore_dynasty:0 "§YRestore Dynasty§!"
 to_pt_restore_dynasty_desc:0 "[From.GetName] becomes a [This.GetName] §YImperial Associate §!and proper §YSpartakon §!dynasty member returns on their throne."
 