l_english:
 pantheon_worship_rebels_army:0 "$RELIGION$ Army"
 pantheon_worship_rebels_demand_desc:0 "The religious rebels fight for the $RELIGION$ religion. They demand that we recognize its supremacy or at the very least cease our efforts to convert them and let them worship in peace."
 pantheon_worship_rebels_desc:0 "Religious fanatics tend to rise up in provinces controlled by nations of a different faith. They seek to spread their faith and smite all unbelievers."
 pantheon_worship_rebels_name:0 "$RELIGION$ Zealots"
 pantheon_worship_rebels_title:0 "Religious"
 pantheon_worship_rebels_demand:0 "Convert $COUNTRYNAME$"


 scythian_nationalist_rebels_desc:0 "Separatist rebels want freedom for their people. They are well led and equipped, but will tend to stay in provinces of their own culture."
 scythian_nationalist_rebels_demand_desc:0 "The Separatists demand Independence for Skythia."
 scythian_nationalist_rebels_name:0 "Skythian Separtists"
 scythian_nationalist_rebels_title:0 "Skythian Separtists"
 
 # aztlan.txt
 aztlan_worship_rebels_army:0 "$RELIGION$ Army"
 aztlan_worship_rebels_demand_desc:0 "The religious rebels fight for the $RELIGION$ religion. They demand that we recognize its supremacy or at the very least cease our efforts to convert them and let them worship in peace."
 aztlan_worship_rebels_desc:0 "Religious fanatics tend to rise up in provinces controlled by nations of a different faith. They seek to spread their faith and smite all unbelievers."
 aztlan_worship_rebels_name:0 "$RELIGION$ Zealots"
 aztlan_worship_rebels_title:0 "Religious"
 aztlan_worship_rebels_demand:0 "Convert $COUNTRYNAME$"
 
 # elysian_orthodoxy.txt
 elysian_orthodoxy_rebels_army:0 "$RELIGION$ Army"
 elysian_orthodoxy_rebels_demand_desc:0 "The religious rebels fight for the $RELIGION$ religion. They demand that we recognize its supremacy or at the very least cease our efforts to convert them and let them worship in peace."
 elysian_orthodoxy_rebels_desc:0 "Religious fanatics tend to rise up in provinces controlled by nations of a different faith. They seek to spread their faith and smite all unbelievers."
 elysian_orthodoxy_rebels_name:0 "$RELIGION$ Zealots"
 elysian_orthodoxy_rebels_title:0 "Religious"
 elysian_orthodoxy_rebels_demand:0 "Convert $COUNTRYNAME$"
 
 # native.txt
 native_rebels_army:0 "Native Separtist Army"
 native_rebels_demand_desc:0 "The [Root.GetCouncilsName] have had enough of the violent expansionism into the lands of their brethren. They demand that we cease all such wars and greater autonomy for their people that live inside our borders."
 native_rebels_desc:0 "The Native Separtists are violently opposed to our militaristic expansionism into the lands of local powers in the New World. They have risen up in support of their brethren outside the country. Any territories held by the rebels may unceremoniously defect if the war drags on for too long."
 native_rebels_name:0 "$COUNTRY$ Native Separtist Rebels"
 native_rebels_title:0 "Native Separtist"
 native_rebels_demand:0 "Increased autonomy and in provinces with the culture native to the §YNew World§! and immidiate cessation of all offensive wars against their brethren."
 