l_english:
 
 # 00_scripted_functions.txt
 ALBANIAN_MAJORITY:0 "§RAlbanian Majority§!"
 BEING_SETTLED:0 "§RProvince is still being settled.§!\n"
 BELONGS_TO_ELG:0 "The province belongs to Konstantinia"
 BYZ_FLIGHT_CONDITION:0 "£icon_x_font£Do NOT have the modifier §YRoman Flight§!"
 CAN_ONLY_COLONISE_PRIMARY_CULTURE_GROUP:0 "Can only colonise primary culture (§Y[From.Culture.GetGroupName]§!) group provinces."
 HOMELANDS:0 "§YHeartland§! provinces will be cored automatically.\n"
 IMPERIAL_CAPITAL:0 "Neo Konstantinoupolis is our de jure capital and thus the court can only be moved into it."
 IS_MIGRATORY:0 "§RIs Migratory§!"
 LOCAL_CULTURE:0 "§RLocal Culture§!"
 NHS_HAS_LOTS_OF_PEOPLE_HALVED_MODIFIER:0 "As long as we have §YBrave New World§! modifier we can only colonise a single province at a time."
 NHS_HAS_LOTS_OF_PEOPLE_MODIFIER:0 "As long as we have §YEager Settlers§! modifier we can only colonize a single province at a time."
 NHS_HAS_LOTS_OF_PEOPLE_WINTER_MODIFIER:0 "As long as we have §YTrials of Elysia§! modifier we can only colonise a single province at a time."
 NHS_MILITARY_ORDER:0 "§RAs a Military Order we are limited to our capital province.§!\n"
 NHS_NO_RENESSIANCE:0 "£icon_x_font£Has embraced Renaissance"
 NHS_OV_EFFORT:0 "One of the following must be true:\n £icon_x_font£Does not have '§YSecuring Supply Lines§!' triggered modifier\n £icon_x_font£We or any of our subjects own a neighboring province"
 NHS_RESTRICTED:0 "§ROur overlord has restricted us from colonising here§!"
 NHS_STARTING_MODIFIERS:0 "§RDue to our limited colonial range we have to fully colonise nearby province first.§!\n"
 NHS_TREARY_OF_LANTANOPOLIS:0 "§YTreaty of Lathanopolis§! §Rprevents§! us from colonising this province.\n"
 OWNS_A_PROVINCE_IN_EUROPE:0 "£icon_x_font£Owns or subject owns at least one province in §YEurope§!"
 TO_WAIT_A_MONTH:0 "§RPlease wait until the start of the next month for the triggered modifiers to adjust.§!"
 TRIBAL_DEV_CANNOT_EXPLOIT:0 "£icon_x_font£Does NOT have the province modifier §YTribal Development§!"
 VINLAND_CAPITAL:0 "Capital can only be moved here via '§YMove Capital Westward§!' decision."
 