l_english:
 nhs_elysian_arsenal_desc:0 "§lThe Arsenal of Elysia, a massive shipbuilding industry, is an enlarged version of an existing structure in the city of Venice. With many specialized structures designed for building one specific part of a ship, the Arsenal is capable of putting to sea warships faster than any nation in the world - except, perhaps, the rapidly-declining Venice.§!"
 to_imperial_protectorate_adm_mod_tt:0 "Overlord is ahead in §YAdministrative Technology§!"
 to_imperial_protectorate_dip_mod_tt:0 "Overlord is ahead in §YDiplomatic Technology§!"
 to_imperial_protectorate_mil_mod_tt:0 "Overlord is ahead in §YMilitary Technology§!"
 
 # 00_subject_types.txt
 elysian_subject:0 "Exarchate"
 elysian_subject_is_our:0 "§Y$NAME$§! is our Exarchate."
 elysian_subject_long_desc:0 "The Exarchate is a provincial post which is provided with increased political and military authority over a particularly large and important region."
 elysian_subject_title:0 "Exarchate"
 elysian_subject_title_plural:0 "Exarchates"
 elysian_subject_varangian:0 "Kleisoura"
 elysian_subject_varangian_title:0 "Kleisoura"
 elysian_subject_varangian_is_our:0 "§Y$NAME$§! is our Military Order."
 elysian_subject_varangian_long_desc:0 "The Kleisoura is a small military post focused almost entirely on fortifying a frontier region against foreign invasion, with elite soldiers garrisoning many of its towns and forts at all times."
 elysian_subject_varangian_title_plural:0 "Kleisouras"
 nhs_imperial_associate:0 "Imperial Associate"
 nhs_imperial_associate_title:0 "Imperial Associate"
 nhs_imperial_associate_is_our:0 "§Y$NAME$§! is our Imperial Associate."
 nhs_imperial_associate_long_desc:0 ""
 nhs_imperial_associate_title_plural:0 "Imperial Associates"
 to_confederation_subject:0 "Confederation Member"
 to_confederation_subject_title:0 "Junior Confederation Member"
 to_confederation_subject_is_our:0 "§Y$NAME$§! is a member in our Confederation."
 to_confederation_subject_long_desc:0 "TODO"
 to_confederation_subject_title_plural:0 "Junior Confederation Members"
 to_elysian_governor:0 "Despotate"
 to_elysian_governor_is_our:0 "§Y$NAME$§! is our Despotate."
 to_elysian_governor_long_desc:0 "The office of Despot was created to oversee the ongoing in Elysia when as the throne moved back to the Old World."
 to_elysian_governor_title:0 "Despotate"
 to_elysian_governor_title_plural:0 "Despotates"
 to_imperial_protectorate:0 "Imperial Protectorate"
 to_imperial_protectorate_title:0 "Imperial Protectorate"
 to_imperial_protectorate_is_our:0 "§Y$NAME$§! is our Imperial Protectorate."
 to_imperial_protectorate_long_desc:0 "Imperial Protectorates transfer §Y50%§! of their trade power to their overlord in exchange for military protection. They gain §G+15.0%§! Goods Produced Modifier, §G+20.0%§! Production Efficiency, §G+25.0%§! Institution Spread, and §G-10%§! Technology Cost in any category the overlord is ahead in.\nThe overlord receives §G+1§! Merchant, §G+5.0%§! Global Trade Power, and §G-5.0%§! Trade Company Investment Cost if the Protectorate has at least §Y51%§! of the province trade power in their home trade node.\nIf an Imperial Protectorate's liberty desire raises above §Y75§! the overlord gets §R-25§! Governing Capacity and §R-5.0%§! Trade Efficiency.\nThe overlord can call a protectorate into their own war in exchange for an opinion penalty."
 to_imperial_protectorate_title_plural:0 "Imperial Protectorates"
 