l_english:
 
 # 00_scripted_functions.txt
 BEING_SETTLED:0 "§RProvince is still being settled.§!\n"
 BYZ_FLIGHT_CONDITION:0 "£no£Do NOT have the §YRoman Flight§! modifier"
 COLONIAL_NATIONS_CANNOT_COLONIZE:0 "Colonial Nations are unable to colonize."
 IMPERIAL_CAPITAL:0 "Neo Konstantinoupolis is our de jure capital and thus the court can only be moved into it."
 IS_MIGRATORY:0 "§RIs Migratory§!"
 LOCAL_CULTURE:0 "§RLocal Culture§!"
 NHS_HAS_LOTS_OF_PEOPLE_HALVED_MODIFIER:0 "As long as we have §YBrave New World§! modifier we can only colonize a single province at a time."
 NHS_HAS_LOTS_OF_PEOPLE_MODIFIER:0 "As long as we have §YEager Settlers§! modifier we can only colonize a single province at a time."
 NHS_HAS_LOTS_OF_PEOPLE_WINTER_MODIFIER:0 "As long as we have §YTrials of Elysia§! modifier we can only colonize a single province at a time."
 NHS_MILITARY_ORDER:0 "§RAs a Military Order we are limited to our capital province.§!\n"
 NHS_NO_RENESSIANCE:0 "£no£Has embraced Renaissance"
 NHS_OV_EFFORT:0 "One of the following must be true:\n £no£Does not have '§YSecuring Supply Lines§!' triggered modifier\n £no£We or any of our subjects own a neighboring province"
 NHS_RESTRICTED:0 "§ROur overlord has restricted us from colonising here.§!"
 NHS_STARTING_MODIFIERS:0 "§RDue to our limited colonial range we have to fully colonize nearby province first.§!\n"
 NHS_TREARY_OF_LANTANOPOLIS:0 "§YTreaty of Elpida§! §Rprevents§! us from colonising this province.\n"
 OWNS_A_PROVINCE_IN_EUROPE:0 "£no£Owns or subject owns at least one province in §YEurope§!"
 PROVINCE_HAS_PARA_BELLUM:0 "§R- §YPara Bellum§! province modifier prevents us from Scorching Earth in this province.§!"
 TO_CANNOT_COLONISE_MANPOWER_SHORTAGE:0 "We cannot colonize as we are in the same Technology Group as our Overlord (§YExiled Roman§!), who has §YManpower Shortage§! modifier."
 TO_CAN_NO_LONGER_ADD_TO_HRE:0 "We can no longer add provinces to the Holy Roman Empire."
 TO_COLONIAL_TREATY:0 "Colonial Treaty from a recently lost war prevents us from colonizing here."
 TO_CONQUEST_OF_ROME_EVENT_ACTIVE:0 "§YConquest of Rome§! event is NOT active."
 TO_DOES_NOT_HAVE_CULTURAL_SUFFERENCE_MOD:0 "£no£Does NOT have the §YCultural Sufferance§! province modifier"
 TO_DOF_IS_CHRISTIAN_OR_MUSLIM:0 "You have to be in §YChristian§! or §YMuslim§! religion group."
 TO_DOF_IS_CHRISTIAN_OR_MUSLIM_OR_COMPLETED_OLD_GODS:0 "You have to be in §YChristian§! or §YMuslim§! religion group, or have completed §YThe Old Gods§! mission."
 TO_HAS_ALBANIAN_MAJORITY:0 "\n£no£Does NOT have the §YAlbanian Majority§! province modifier"
 TO_HAS_ALBANIAN_MAJORITY2:0 "\n£no£Does NOT have the §YArbanitai Majority§! province modifier"
 TO_IS_AN_EXARCH:0 "§R-Is an Exarch§!"
 TO_OWNER_NOT_ELYSIAN_CULTURE:0 "£no£Owner is NOT in §YElysian§! culture group."
 TO_WAIT_A_MONTH:0 "§RPlease wait until the start of the next month for the triggered modifiers to adjust.§!"
 TRIBAL_DEV_CANNOT_EXPLOIT:0 "£no£Does NOT have the §YTribal Development§! province modifier"
 VINLAND_CAPITAL:0 "Capital can only be moved here via '§YMove Capital Westward§!' decision."
 