l_english:
 QQF:0 "Jicarilla"
 QQG:0 "Mescalero"
 QQH:0 "Chiracahua"
 QQI:0 "Yavapai"
 nhs_accepts_one_vinlandic_culture_tt:0 "Accepts a culture in §YNorse§! culture group"
 nhs_is_elysia_tt:0 "One of the following must be true:\n Is §YElysia§!\n Is §YElysian Empire§!\n Is §YFirst Elysian Republic§!\n Is §YSecond Elysian Republic§!\n Is §YRevolutionary Elysia§!"
 trading_with_helluland_tooltip:0 "Is trading with Helluland"
 trading_with_markland_tooltip:0 "Is trading with Markland"
 trading_with_vinland_tooltip:0 "Is trading with Vinland"
 
 # 01_NHS_scripted_triggers.txt
 calusan:0 "Calusan"
 nhs_accepts_one_elysian_culture_tt:0 "Accepts a culture in §YElysian§! culture group"
 nhs_at_least_25_dev:0 "Has less than §Y25%§! of our total development"
 nhs_ei_repaired_tt:0 "Can be restored by a decision if you meet the one of the requirements below."
 nhs_elysia_under_pu_tt:0 "§YElysia§! is junior partner in a personal union with us"
 nhs_euro_elysian_diplomatic_channels_tt:0 "Has established proper diplomatic channels"
 nhs_has_rediscovered_europe_tt:0 "Pytheas has completed his voyage"
 nhs_natives_no_privileges_tooltip:0 "Has revoked Council privileges"
 nhs_natives_privileges_tooltip:0 "Hasn't revoked Council privileges"
 nhs_not_been_rebuild_yet_tt:0 "Has not yet been properly restored by a nation that meets the modifier's requirements."
 nhs_recently_conquered_improvement_tt:0 "[Root.GetName] has been conquered recently"
 tonkawan:0 "Tonkawan"
 