l_english:
 msg_elysian_debt:0 "§MThe Elysians will consider us to be in their debt (WIP)§!"
 msg_elysian_debt_tt:0 "Lose §R10§! Legitimacy due to not sharing religion with §YElysia§!."
 msg_ignore_reform_corr_tt:0 "§GSwitching to this reform ignores corruption penalty.§!"
 nhs_add_center_of_trade_1_tt:0 "Local §YCenter of Trade§! level is set to §Y1§!. If level §Y1§! Center of Trade already exists, owner receives §Y50§!£icon_font_gold£"
 nhs_add_center_of_trade_2_tt:0 "Local §YCenter of Trade§! level is set to §Y2§!. If level §Y2§! Center of Trade already exists, owner receives §Y100§!£icon_font_gold£"
 nhs_add_center_of_trade_3_tt:0 "Local §YCenter of Trade§! level is set to §Y3§!. If level §Y3§! Center of Trade already exists, owner receives §Y500§!£icon_font_gold£"
 
 # 01_nhs_scripted_effects.txt
 NHS_SKOROS_FALLS:0 "Outclassed by Eastern Silk"
 NHS_SKOROS_ISOLATIONISM:0 "Elysian Isolationism"
 nhs_all_embrace_engligh:0 "Every owned province embraces Enlightenment"
 nhs_all_embrace_feud:0 "Every owned province embraces Feudalism"
 nhs_all_embrace_global:0 "Every owned province embraces Global Trade"
 nhs_all_embrace_manuf:0 "Every owned province embraces Manufactories"
 nhs_all_embrace_neww:0 "Every owned province embraces Colonialism"
 nhs_all_embrace_print:0 "Every owned province embraces Printing Press"
 nhs_all_embrace_rene:0 "Every owned province embraces Renaissance"
 nhs_enough_delay_flight_tt:0 "§RWe have delayed the flight long enough, our next choice must be final.§!"
 nhs_high_patriarch_authority_10:0 "\n§MBeing at or above 10 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_10_below:0 "\n§MBeing below 10 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_20_below:0 "\n§MBeing below 20 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_25:0 "\n§MBeing at or above 25 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_30:0 "\n§MBeing at or above 30 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_5_below:0 "\n§MBeing below 5 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_75_below:0 "\n§MBeing below 75 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_80:0 "\n§MBeing at or above 80 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_80_below:0 "\n§MBeing below 80 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_90:0 "\n§MBeing at or above 90 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_95:0 "\n§MBeing at or above 95 Patriarch Authority grants us:§W"
 nhs_high_patriarch_authority_95_below:0 "\n§MBeing below 95 Patriarch Authority grants us:§W"
 nhs_self_governance_tt:0 "§MAs long as the Shqipëri govern themselves the negative effects of the modifier are ignored.§!"
 nhs_settler_heritage_0_1_tt:0 "Replace §YManpower Shortage§! with §YSettler Heritage§!\nEffective change:\nNational Manpower Modifier: §G+10.0%§!\nNaval Force-limit Modifier: §G+10.0%§!\nLand Maintenance Modifier: §G-10.0%§!\nNaval Maintenance Modifier: §G-30.0%§!\nCavalry Cost: §G-20.0%§!\nShipbuilding Time: §G-50.0%§!\nShip Costs: §G-50.0%§!\nAvailable Mercenaries: §G+35.0%§!\nCavalry to Infantry Ratio: §G+10.0%§!\n"
 nhs_settler_heritage_0_2_tt:0 "Replace §YManpower Shortage§! with §YSettler Heritage§!\nEffective change:\nNational Manpower Modifier: §G+20.0%§!\nLand Force-limit Modifier: §G+5.0%§!\nNaval Force-limit Modifier: §G+10.0%§!\nLand Maintenance Modifier: §G-20.0%§!\nNaval Maintenance Modifier: §G-40.0%§!\nCavalry Cost: §G-30.0%§!\nShipbuilding Time: §G-100.0%§!\nShip Costs: §G-100.0%§!\nAvailable Mercenaries: §G+45.0%§!\nCavalry to Infantry Ratio: §G+20.0%§!\n"
 nhs_starting_flagship_tt:0 "\nFlagship named §YAgia Theotoke§! becomes available for duty in §YElysia§!."
 nhs_true_nation_mission_trigger_reduce_tt:0 "§YA True Nation§! mission can be completed §G5§! years ealier."
 nhs_update_albanian_majority_tt:0 "Replace §YAlbanian Majority§! with §YShqipproi Majority§!\n  Effective change:\n   Local Production Efficiency: §G+20.0%§!\n   Local Tax Modifier: §G+20.0%§!\n   Local Missionary Strength: §G+2.0%§!\n   Local Manpower Modifier: §G+20.0%§!\n   Local Defensiveness: §R-25.0%§!\n   Minimum Local Autonomy: §G-20.00§!"
 vov_heir_to_general:0 "Convert Heir to General"
 vov_ruler_to_general:0 "Convert Ruler to General"
 
 # 01_nhs_scripted_effects_estates.txt
 nhs_native_priv_designate_development_zones_late:0 "Designated Development Zones"
 nhs_native_priv_divide_et_impera_early:0 "Divide et Impera"
 nhs_native_priv_divide_et_impera_mid:0 "Divide et Impera"
 nhs_native_priv_increase_tribute_late:0 "Increased Tributes"
 nhs_native_priv_increase_tribute_mid:0 "Increased Tributes"
 nhs_native_priv_major_pax_romana_early:0 "Major Pax Romana"
 nhs_native_priv_major_pax_romana_mid:0 "Major Pax Romana"
 
 # TO_NAT_scripted_effects.txt
 to_nat_gain_migratory_development_tt:0 "A total of [Root.GetPotentialMigratoryTax]£text_icon_tax_in_text£, [Root.GetPotentialMigratoryProduction] £text_icon_production_in_text£ and [Root.GetPotentialMigratoryManpower] £text_icon_manpower_in_text£ in the capital is transformed into §YMigratory Development§!, which is retained on migration."
 to_nat_integrate_confederation_tt:0 "All nations in our §YConfederation§! will be automatically integrated."
 to_nat_native_displacement_manpower_gain_display_empty_tt:0 "§Y[displace_tribal_development_target.GetName]§! gains §G[origin_province.tribal_manpower_moved.GetValue]§! Base Manpower"
 to_nat_native_displacement_manpower_gain_display_tt:0 "Gain §G[origin_province.tribal_manpower_moved.GetValue]§! Base Manpower in §Y[displace_tribal_development_target.GetName]§!"
 to_nat_native_displacement_manpower_loss_display_tt:0 "Lose §R[origin_province.tribal_manpower_loss.GetValue]§! Base Manpower in §Y[origin_province.GetName]§!"
 to_nat_native_displacement_production_gain_display_empty_tt:0 "§Y[displace_tribal_development_target.GetName]§! gains §G[origin_province.tribal_production_moved.GetValue]§! Base Production"
 to_nat_native_displacement_production_gain_display_tt:0 "Gain §G[origin_province.tribal_production_moved.GetValue]§! Base Production in §Y[displace_tribal_development_target.GetName]§!"
 to_nat_native_displacement_production_loss_display_tt:0 "Lose §R[origin_province.tribal_production_loss.GetValue]§! Base Production in §Y[origin_province.GetName]§!"
 to_nat_native_displacement_tax_gain_display_empty_tt:0 "§Y[displace_tribal_development_target.GetName]§! gains §G[origin_province.tribal_tax_moved.GetValue]§! Base Tax"
 to_nat_native_displacement_tax_gain_display_tt:0 "Gain §G[origin_province.tribal_tax_moved.GetValue]§! Base Tax in §Y[displace_tribal_development_target.GetName]§!"
 to_nat_native_displacement_tax_loss_display_tt:0 "Lose §R[origin_province.tribal_tax_loss.GetValue]§! Base Tax in §Y[origin_province.GetName]§!"
 to_nat_remove_migratory_development_tt:0 "§YMigratory Development§! will be integrated into §YTribal Development§!."
 to_nat_remove_tribal_development_tt:0 "§YTribal Development§! will be automatically integrated in our non-colonial provinces."
 to_nat_to_assign_native_council_tt:0 "§Y[Root.GetCouncilName]§! ([Root.to_native_council_adm.GetValue]/[Root.to_native_council_dip.GetValue]/[Root.to_native_council_mil.GetValue]) becomes ruler."
 to_nat_tribal_development_assimilated_tt:0 "Local §YTribal Development§! is §Gassimilated§!."
 to_nat_will_remove_tribal_development_tier_5_tt:0 "If we have enacted §YSettle Down§! government reform, §YTribal Development§! will be automatically integrated in our non-colonial provinces."
 to_native_reform_law_of_peace:0 "Great Law of Peace"
 to_remove_excess_gov_reforms_points_tt:0 "Removes any excess §YGovernment Reform Progress§!."
 to_remove_native_modifiers_tt:0 "As a result of advances in government we are no longer effected by the modifiers applied to §YNative Government§!. Effective change:\n Diplomatic Relations: §G+1§!\n Institution Spread: §G+25.0%§!\n Monthly Reform Progress Modifier: §G+25.0%§!\n Regiment Cost: §R+25.0%§!\n Minimum Autonomy: §G-50.00§!\n Can use §YExpand Administration§!"
 to_start_spreading_legalism_tt:0 "Gain base §YLegalism§! institution spread in all owned and subject provinces."
 