l_english:
 # Dump your new localisations here, they will be automatically sorted next time the localisation search is run!
to_elysian_sprite_pack:0 "Elysian Sprites"
to_elysian_fire_pack:0 "Greek Fire Sprites"
to_norse_sprite_pack:0 "Vinlandic Sprites"
to_spartan_sprite_pack:0 "Spartan Sprites"