l_english:
 # Collection of TODO localisation strings. Will not be automatically sorted.
 nhs_infrastructure_mission_desc:0 "TODO"

 nhs_aqueducts_mission_desc:0 "TODO"

 nhs_diplomacy_mission_desc:0 "TODO"

 nhs_border_fortifications_mission_desc:0 "TODO"

 nhs_unite_home_region_mission_title:0 "TODO"

 nhs_hegemony_mission_desc:0 "TODO"

 nhs_farming_mission_desc:0 "TODO"

 nhs_alexandrian_library_books_discount_tt:0 "TODO"
 nhs_library_tier1_cost_tt:0 "TODO"
 
 nothingDESC:0 "TODO"
 to_confederation_subject_long_desc:0 "TODO"

 estate_nomadic_tribes_desc:0 "TODO"

 desc_to_nat_colonise_own_modifier:0 "TODO"
 desc_to_nat_native_expansion_modifier:0 "TODO"
 desc_to_nat_unite_continent_modifier:0 "TODO"
 desc_to_nat_expand_overseas_modifier:0 "TODO"