l_english:
 # Dump your new localisations here, they will be automatically sorted next time the localisation search is run!
 to_elysian_sprite_pack:0 "Elysian Sprites"
 to_elysian_fire_pack:0 "Greek Fire Sprites"
 to_norse_sprite_pack:0 "Vinlandic Sprites"
 to_spartan_sprite_pack:0 "Spartan Sprites"
 elysiangfx_sprite_pack:0 "Base Elysian Sprites"
 
 to_province_is_or_accepts_religion_both_orthodox_tt:0 "The Religion of §Y[Root.GetName]§! is §YEastern§! or §YElysian Orthodox§! and is either the State or the Syncretic Religion of the owner."
 to_province_is_or_accepts_religion_both_orthodox_exarch_tt:0 "The Religion of §Y[Root.GetName]§! is §YEastern§! or §YElysian Orthodox§! and is either the State or the Syncretic Religion of the owner or the overlord (§Y[Root.Owner.Overlord.GetName]§!)."
 
 desc_nhs_greekfire_later:0 "We know the formula and mechanisms to use Greek Fire in naval combat."
 nhs_greekfire_later:0 "Greek Fire"
 
 desc_nhs_greekfire_later_w:0 "Our reliance on Greek Fire has left parts military crippled in its absence."
 nhs_greekfire_later_w:0 "Lost Naphtha Supplies"
 
 nhs_enable_greek_fire_later_decision_tt:0 "Enables decision '§YDelve Into the Secrets of Greek Fire§!'."
 
 nhs_enable_greek_fire_later_title:0 "Delve Into the Secrets of Greek Fire"
 nhs_enable_greek_fire_later_desc:0 "With the documents detailing the production of legendary 'Greek Fire' in our hands, we are regretfully informed that the supply of naphtha, a viscous black liquid critical to its production, left available to us is not sufficient to begin its production on a military scale. Not only that but the information on its practical deployment seems sparse at best. A significant investment will be needed both to mobilize explorers to scour the lands for the substance, and to prepare our military for using it."
 
 nhs_naphtha_send_scouts_tt:0 "§YExplorers will be sent out in search for naphtha.§!"

 desc_nhs_fire_reform_w:0 ""
 desc_nhs_fire_reform_w_update:0 ""

 desc_nhs_fire_reform_w_later:0 ""
 nhs_fire_reform_w_later:0 "Crippled Military"

 heralds_cooldown_tooltip:0 "Has not dispatched the heralds in last §Y5§! years"

 nhs_giftaction_but_why_tt:0 "The recipient is §Y[TUR.GetName]§!, but why would you do that?"

 nhs_remove_albanian_majority_tt:0 "§YAlbanian Majority§! will be removed from [This.GetName]."
 nhs_remove_albanian_majority2_tt:0 "§YShqipproi Majority§! will be removed from [This.GetName]."

 native_reformed_desc:0 "This is a former native tribe that has adapted to new ideas and modernised the government structure."

 nhs2_treaty_of_lantanopolis_colonial_growth_reduction:0 "Adherence to the Treaty of Lanthanopolis"
 desc_nhs2_treaty_of_lantanopolis_colonial_growth_reduction:0 "As part of the Treaty of Lanthanopolis, the colonists are rapidly emigrating our of the province."
 
 nhs_enables_reform2_tt:0 "Enables decision '§YReligious Reform:§! Legitimise The Faith'"
 nhs_enables_reform3_tt:0 "Enables decision '§YReligious Reform:§! Consolidate Elysian Rites'"
 nhs_enables_reform4_tt:0 "Enables decision '§YReligious Reform:§! Mend the Schism'"
 
 nhs_provinces_with_elysian_orthodoxy_tt:0 "Province that follow §YElysian Orthodox§! religion"

 nhs_owned_by_elysia_or_subject_tt:0 "Owned by §Y[GetExistingElysiaName]§! or its Subjects."

 nhs_generous_supplies_dev_ideas_bonus_tt:0 "Due to the §Ggenerous§! amount of supplies we have taken, we gain the following benefits:"
 nhs_plentiful_supplies_dev_ideas_bonus_tt:0 "Due to the §Gplentiful§! supplies we have taken, we gain the following benefits:"
 nhs_a_new_start_idea_tt:0 "Add §YA New Start§! development idea."
 nhs_population_boom_idea_tt:0 "Add §YPopulation Boom§! development idea."
 nhs_planned_metropoles_idea_tt:0 "Add §YPlanned Metropoles§! development idea."

 nhs_disabled_patriarch_land_events_tt:0 "The Church will no longer make such demands for the duration of §Y[Root.Monarch.GetName]§! lifetime."

 to_in_a_war_with_native_country_tt:0 "§Y[Root.GetName]§! is a leader in an §Yoffensive war§! against a country with §YNative§! or §YReformed Native§! government with a culture native to the §YNew World§!."
 to_not_in_a_war_with_native_country_tt:0 "§Y[Root.GetName]§! is NOT a leader in an §Yoffensive war§! against a country with §YNative§! or §YReformed Native§! government with a culture native to the New World."
 to_has_a_province_with_native_culture_tt:0 "§Y[Root.GetName]§! owns a province with a culture native to the §YNew World§!, which §Yhas§! or §ghad§! §YTribal Development§!."
 to_not_has_a_province_with_native_culture_tt:0 "§Y[Root.GetName]§! does NOT own a province with a culture native to the §YNew World§!, which §Yhas§! or §ghad§! §YTribal Development§!."
 to_has_national_bank_idea_tt:0 "Has §YNational Bank§! economic idea"

 nhs_area_can_no_longer_build_shipyard_tt:0 "Can no longer build §YShipyards§! and §YGrand Shipyards§! in §Y[950.GetAreaName]§! Area."

 nhs_hrv_loyal_hellenic:0 "Inspired Preachers"
 desc_nhs_hrv_loyal_hellenic:0 "Preachers of the Old Gods are inspired for having triumphed over the preachers of the Christ."
 to_cm1_modify_constrained_resources_tt:0 "Modify §YConstrained Resources§! by\nColonial Range: §G+20.0%§! (Total: §R-80.0%§!)"

 nhs_vov_farmenn_minnus:0 "Lack of Mercantile Support"
 desc_nhs_vov_farmenn_minnus:0 ""

 EST_VAL_DISSIDENTS_CRUSHED:0 "Dissent Crushed"
 
 nhs2_keep_first_reform_native_tt:0 "We will keep the army reform: §YConscripting Native Warriors§!"
 nhs2_keep_first_reform_traditional_tt:0 "We will keep the army reform: §YExpanded the Militia§!"
 nhs2_keep_first_reform_janissary_tt:0 "We will keep the army reform: §YOrhan's Janissaries§!"

 to_tribal_dev_emigration_reason_estate_tt:0 "To prevent this from happening in the future we have to increase the §Y[Root.Owner.GetCouncilsName] Loyalty§! above §Y30§!."
 to_tribal_dev_emigration_reason_no_estate_tt:0 "To prevent this from happening in the future we have to ensure our Native Uprising Chance is at least §G-100.0%§!."

 TO_OWNER_NOT_ELYSIAN_CULTURE:0 "£icon_x_font£Owner is NOT in §YElysian§! culture group."
 
 to_monuments_later_tt:0 "Since there is an ongoing §Yconstruction§! in the province, the §Ymonument§! will become visible after the work is completed."
 to_monuments_later_missionary_tt:0 "Since there is an ongoing §Ymissionary Work§! in the province, the §Ymonument§! will become visible after the work is completed."
 to_monuments_later_colonist_tt:0 "As long as there is a Colonist §YPromoting Settlement Growth§! in the province, the §Ymonument§! will not be visible."

 nhs_capital_monument_monarchy_leviathan_tt:0 "Yearly Legitimacy: §G+1.00§!\nMonthly Heir Claim Increase: §G+0.10§!"
 nhs_capital_monument_monarchy_tt:0 "Yearly Legitimacy: §G+1.00§!"
 nhs_capital_monument_theocracy_tt:0 "Yearly Devotion: §G+1.00§!"
 nhs_capital_monument_republic_tt:0 "Reelection Cost: §G-10.0%§!"

 to_nhs_handicap_settlers_subject:0 "Overlord has §YManpower Shortage§!"
 to_nhs_settler_heritage_subject:0 "Overlord has §YSettler Heritage§!"
 to_nhs_settler_heritage_two_subject:0 "Overlord has §YSettler Heritage§!"
 to_nhs_settler_heritage_three_subject:0 "Overlord has §YSettler Heritage§!"

 nhs_culture_changes_in_capital_area_tt:0 "Provinces in our Capital Area (§YElysia§!) will gain a §YCore§!, become §YGreek§! and convert to our religion (§Y[Root.Religion.GetName]§!) when we finish colonising them."
 to_nat_td_res_population_elysia_area_tt:0 "Upon colonization the culture and religion of the province will become §YGreek§! and convert to our religion (§Y[Root.Religion.GetName]§!) to the colonizer's, since the province is in our Capital Area (§Y[Root.GetAreaName]§!).\n"

 to_country_or_subject_or_subject_of_subject_holds_ROOT: "Owned by §Y[Root.GetName]§! or its subjects, or the subjects of their subjects."
 
 legacy_of_the_flight:0 "Legacy of the Flight"
 legacy_of_the_flight_desc:0 "Our harrowing journey to Elysium and the subsequent beginnings of our nation have shown where our priorities should lie. May we never forget our ancestors' passage or squander the opportunity they gave us."

 constantinople_never_again_subject:0 "Overlord has §YNever Again Falter§! National Idea"
 ALL_GREEK_PROVINCES_AND_953:0 "All Byzantine Provinces and Constantinople"
 to_nhs_is_in_war_with_invasion_cb_tt:0 "Is in an §Yoffensive war§! using §YInvasion§! Casus Belli"
 to_nhs_is_defending_against_invader_tt:0 "Is in §Ydefensive war§! against a country that is NOT in §YByzantine§! culture group and owns at least one §YGreek§! province"
 nhs_enable_invasion_cb_tt:0 "Gain §YInvasion§! Casus Belli, which can be used to liberate §YGreek§! provinces from foreign overlords."

 nhs_enables_begin_invasion_tt:0 "Enables decision '§YBegin the Invasion Effort§!'"

 elysian_subject_varangian_no_overlord_dow:0 "You can't declare war on your kleisouras."
 elysian_subject_no_overlord_dow:0 "You can't declare war on your exarchs."
 to_confederation_subject_no_overlord_dow:0 "You can't declare war on your junior confederation members."

 nhs2_army_reforms.4.f:0 "Invest in the modernization of our cavalry."
 nhs2_army_reforms.4.t5:0 "§MThe Roman Empire has long relied on elite cavalry formations to win battles and wage wars. Horse archers, light skirmishers, Latin knights, cataphracts - we have used every kind of horseman the world has. Just because it is more difficult to utilize cavalry in modern warfare, however, does not mean that we should abandon a tested method of war. Hussars, dragoons, cuirassers... Europe has all manner of effective horse soldiery to draw upon.§!"
 nhs2_army_reform_cavalry2:0 "Hussars and Cataphracts"
 desc_nhs2_army_reform_cavalry2:0 "The Roman Empire has long relied on elite cavalry formations to win battles and wage wars. Horse archers, light skirmishers, Latin knights, cataphracts - we have used every kind of horseman the world has. Just because it is more difficult to utilize cavalry in modern warfare, however, does not mean that we should abandon a tested method of war. Hussars, dragoons, cuirassers... Europe has all manner of effective horse soldiery to draw upon."

 to_byz_dont_die:0 "Plot Armor"
 desc_to_byz_dont_die:0 "=)"
 
 nhs_albanian_to_shqipproi_all_provinces_tt:0 "§YEvery§! province with §YAlbanian§! culture becomes §YShqipproi§!."

 nhs_albanian_integration_fails_tt:0 "A setback, but the process will continue..."

 to_enforce_colony_religion_desc:0 "Religion of §Y[From.GetName]§! changes to §Y[Root.Religion.GetName]§!.\n§Y[From.GetName]§! gets §R[From.GetEnforceReligionLD]§! Liberty Desire."
 to_enforce_colony_religion_title:0 "§MEnforce Religion§!"
 to_enforce_colony_religion_tooltip:0 "Religion of §Y[From.GetName]§! changes to §Y[Root.Religion.GetName]§!.\n§Y[From.GetName]§! gets §R[From.GetEnforceReligionLD]§! Liberty Desire."

 to_enforce_colony_culture_desc:0 "Culture of §Y[From.GetName]§! changes to §Y[Root.GetEnforceCultureCulture]§!.\n§Y[From.GetName]§! gets §R25§! Liberty Desire."
 to_enforce_colony_culture_title:0 "§MEnforce Culture§!"
 to_enforce_colony_culture_tooltip:0 "Culture of §Y[From.GetName]§! changes to §Y[Root.GetEnforceCultureCulture]§!.\n§Y[From.GetName]§! gets §R25§! Liberty Desire."


 fifty_tt:0 "50"
 hundred_tt:0 "100"
 to_primary_culture_tt:0 "[Root.Culture.GetName]"
 
 to_nhs_exarch_monument_mod_transfer_subject_tt:0 "\n§YAdditional notes§!:\nIf the province is owned by an §YExarch§! all global modifiers will be shared with the overlord (§Y[Root.Owner.Overlord.GetName]§!) if the overlord meets the requirements."
 to_nhs_exarch_monument_mod_transfer_tt:0 "\n§YAdditional notes§!:\nIf the province is owned by an §YExarch§! all global modifiers will be shared with the overlord (§Y[Root.Owner.GetName]§!) if the overlord meets the requirements."

 to_nhs_exarch_kleisoura_monument_mod_transfer_tt:0 "\n§YAdditional notes§!:\nIf the province is owned by an §YExarch§! or a §YKleisoura§! all global modifiers will be shared with the overlord (§Y[Root.Owner.Overlord.GetName]§!) if the overlord meets the requirements."
 to_nhs_exarch_kleisoura_monument_mod_transfer_subject_tt:0 "\n§YAdditional notes§!:\nIf the province is owned by an §YExarch§! or a §YKleisoura§! all global modifiers will be shared with the overlord (§Y[Root.Owner.GetName]§!) if the overlord meets the requirements."

 nhs_not_greek_areas_provinces_tt:0 "Is NOT in one of the following areas: §Y[145.GetAreaName]§!, §Y[147.GetAreaName]§!, §Y[148.GetAreaName]§!, §Y[151.GetAreaName]§!, §Y[164.GetAreaName]§!, §Y[150.GetAreaName]§!, §Y[159.GetAreaName]§!"
 nhs_elg_needs_more_privileges_tt:0 "§Y[ELG.GetName]§! must §YLimited§!, §YExpanded§! or §YFull Land Privileges§!."
 nhs_no_missionary_provinces_tt:0 "§MThey§! §Owill not§! §Mreceive territory which has missionary working in it.§!\n"
 nhs_exarch_no_eligible_provinces_tt:0 "There are no eligible provinces in the region that would be immediately ceeded to §Y[ELG.GetName]§!."
 
 nhs_exarch_potential_provinces_konstantinia_balkans_anatolia:0 "that are either in §YBalkan§! or §YAnatolian§! region.\nThey §Owill not§! receive §Y[151.GetName]§! itself"
 nhs_exarch_potential_provinces_konstantinia_balkans:0 "that are in §YBalkan§! region.\nThey §Owill not§! receive §Y[151.GetName]§! itself"
 nhs_exarch_potential_provinces_konstantinia_anatolia:0 "that either have §YByzantine§! culture, are in §YAnatolian§! region, or are in one of the following areas: §Y[145.GetAreaName]§!, §Y[147.GetAreaName]§!, §Y[148.GetAreaName]§!, §Y[151.GetAreaName]§!, §Y[164.GetAreaName]§!, §Y[150.GetAreaName]§!, §Y[159.GetAreaName]§!.\nThey §Owill not§! receive §Y[151.GetName]§! itself"
 
 hagia_sophia_subject_tt:0 "The Religion of §Y[Root.GetName]§! is either §YCatholic§!, §YEastern§! or §YElysian§! §YOrthodox§!, or §YCoptic§! or part of the §YMuslim§! religion group and is either the State or the Syncretic Religion of the owner or the overlord (§Y[Root.Owner.Overlord.GetName]§!)."
 province_is_or_accepts_pagan_exarch_tt:0 "The Religion of §Y[Root.GetName]§! is §YPagan§! and is either the State or the Syncretic Religion of the owner or the overlord (§Y[Root.Owner.Overlord.GetName]§!)."
 to_has_overlords_culture_tt:0 "Has overlord's culture"
 to_has_overlords_accepted_culture_tt:0 "Have culture accepted by overlord"
 
 province_is_or_accepts_christian_exarch_tt:0 "The Religion of §Y[Root.GetName]§! is §YChristian§! and is either the State or the Syncretic Religion of the owner or the overlord (§Y[Root.Owner.Overlord.GetName]§!)."
 province_is_or_accepts_muslim_exarch_tt:0 "The Religion of §Y[Root.GetName]§! is §YMuslim§! and is either the State or the Syncretic Religion of the owner or the overlord (§Y[Root.Owner.Overlord.GetName]§!)."
 province_is_or_accepts_jewish_exarch_tt:0 "The Religion of §Y[Root.GetName]§! is §YJewish§! and is either the State or the Syncretic Religion of the owner or the overlord (§Y[Root.Owner.Overlord.GetName]§!)."
 province_is_or_accepts_catholic_exarch_tt:0 "The Religion of §Y[Root.GetName]§! is §YCatholic§! and is either the State or the Syncretic Religion of the owner or the overlord (§Y[Root.Owner.Overlord.GetName]§!)."

 nhs_por_loses_claims_in_na_tt:0 "§Y[Root.nhs_portugal_tar.GetName]§! and its subjects lose all claims on §YElysium§!."
 nhs_lose_claims_in_sa_tt:0 "§Y[Root.GetName]§! and its subjects lose all claims on §YArkadia§!."
 
 nhs_por_loses_claims_in_na_por_perspective_tt:0 "§Y[Root.GetName]§! and its subjects lose all claims on §YElysium§!."
 nhs_lose_claims_in_sa_por_perspective_tt:0 "§Y[From.GetName]§! and its subjects lose all claims on §YArkadia§!."

 nhs_removes_abandon_heritage_decision_tt:0 "Removes decision §YAbandon our Roman Heritage§!"

 nhs_assisting_the_expedition:0 "Assisting the Expedition"
 desc_nhs_assisting_the_expedition:0 "Our decision to support the expedition was a fruitful one. Men who served under Belisarios are bringing back a wealth of military knowledge and experience."
 
 msg_arrival_events.21.t:0 "The Expedition Has Failed"
 msg_arrival_events.21.d:0 "Unfortunately, the attempt by Belisarios and his men to establish an independent kingdom in the lands to the south has failed. The very few men able to return have already done so, and we will no longer receive the military experience of the expeditionary forces."
 msg_arrival_events.21.a:0 "Damn!"
 
 msg_arrival_events.22.t:0 "The Spartans Refuse To Continue Cooperation"
 msg_arrival_events.22.d:0 "With the outbreak of war between Elysia and [existing_sparta.GetName], the Spartans have refused to continue their cooperation with our generals and soldiers. We will no longer receive their valuable military experience."
 msg_arrival_events.22.a:0 "Damn!"

 to_owns_atlantic_port_tt:0 "Owns an §YAtlantic§! port"
 ab_to_intercontinental_trade:0 "Intercontinental Trade"