import csv
import os
import re
from jinja2 import Template

output_file_loc = "o_localization.txt"
output_file_events = "o_events.txt"

COMPATIBILITY_COLUMN = 1
URL_COLUMN = 2
COMPATIBILITY_PATCH = 3
COMPATIBILITY_PATCH_URL = 4

def parse_id(url):
    result = re.search(r'id=(\d+)', url)
    if result is None:
        raise ValueError(f"Could not parse mod id from url: {url}")
    return result.group(1)

def parse_mod_name(name):
    return name.replace("[", "|").replace("]", "|")

incompatible_mods = []
compatible_mods = []
compatibility_patches = []
with open('Compatibility - List1.tsv') as file:
    rd = csv.reader(file, delimiter="\t", quotechar='"')
    for i, row in enumerate(rd):
        if i == 0:
            continue
        if len(row) < 3 or row[COMPATIBILITY_COLUMN] not in ['yes', 'no']:
            continue
        mod_id = parse_id(row[URL_COLUMN])
        mod_name = row[0].strip()
        if row[COMPATIBILITY_COLUMN] == 'no':
            incompatible_mod_entry = {"name": mod_name, "mod_id": mod_id}
            if len(row) >= COMPATIBILITY_PATCH_URL + 1 and row[COMPATIBILITY_PATCH] != "":
                compatibility_patch_id = parse_id(row[COMPATIBILITY_PATCH_URL])
                incompatible_mod_entry["compatibility_patch"] = row[COMPATIBILITY_PATCH]
                compatibility_patches.append({"name": row[COMPATIBILITY_PATCH],
                                              "mod_id": compatibility_patch_id,
                                              "parent_mod": mod_name})
            incompatible_mods.append(incompatible_mod_entry)
        else:
            compatible_mods.append({"name": mod_name, "mod_id": mod_id})

with open(output_file_loc, "w", encoding="utf-8-sig") as file_loc:
    file_loc.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    for mod in incompatible_mods:
        mod_name = parse_mod_name(mod["name"])
        file_loc.write(f" to_mod_{mod['mod_id']}_name_tt:0 \"§Y{mod_name}§!\"\n")
        if "compatibility_patch" in mod:
            file_loc.write(
                f" to_mod_{mod['mod_id']}_compatibility_tt:0 \"{mod_name} (With Compatibility Patch: {parse_mod_name(mod["compatibility_patch"]["name"])})\"\n")
    for mod in compatible_mods:
        file_loc.write(f" to_mod_{mod['mod_id']}_name_tt:0 \"{parse_mod_name(mod['name'])}\"\n")
    for mod in compatibility_patches:
        file_loc.write(f" to_mod_{mod['mod_id']}_name_tt:0 \"{parse_mod_name(mod['name'])} (§RMissing Parent Mod!§!)\"\n")

template = Template('''namespace = to_compatibility_check
    
country_event = {
    id = to_compatibility_check.1
    title = to_compatibility_check.1.t
    desc = to_compatibility_check.1.d
    picture = TO_STEAM_WORKSHOP_eventPicture
    
    is_triggered_only = yes
    
    trigger = {
        ai = no
        if = {
            limit = {
                has_global_flag = to_only_show_incompatibility_on_differences
            }
            OR = {
                {%- for mod in incompatible_mods %}
                AND = {
                    is_mod_active = "{{ mod['name'] }}"
                    NOT = { has_global_flag = to_mod_{{ mod['mod_id'] }}_detected }
                    {%- if "compatibility_patch" in mod %}
                    NOT = { is_mod_active = "{{ mod['compatibility_patch']['name'] }}" }
                    {%- endif %}
                }
                {%- endfor %}
            }
        }
        else = {
            OR = {
                {%- for mod in incompatible_mods %}
                AND = {
                    is_mod_active = "{{ mod['name'] }}"
                    {%- if "compatibility_patch" in mod %}
                    NOT = { is_mod_active = "{{ mod['compatibility_patch']['name'] }}" }
                    {%- endif %}
                }
                {%- endfor %}
            }
        }
    }
    
    immediate = {
        hidden_effect = {
            set_global_flag = to_incompatible_mods_active
            {%- for mod in incompatible_mods %}
            if = {
                limit = {
                    is_mod_active = "{{ mod['name'] }}"
                }
                set_global_flag = to_mod_{{ mod['mod_id'] }}_detected
            }
            {%- endfor %}
        }
    }
    
    option = {
        name = to_compatibility_check.1.a
        custom_tooltip = to_incompatible_mods_active_tt
        {%- for mod in incompatible_mods %}
        if = {
            limit = {
                is_mod_active = "{{ mod['name'] }}"
                {%- if "compatibility_patch" in mod %}
                NOT = { is_mod_active = "{{ mod['compatibility_patch']['name'] }}" }
                {%- endif %}
            }
            custom_tooltip = to_mod_{{ mod['mod_id'] }}_name_tt
        }
        {%- endfor %}
        {%- for mod in compatibility_patches %}
        if = {
            limit = {
                is_mod_active = "{{ mod['name'] }}"
                NOT = { is_mod_active = "{{ mod['parent_mod'] }}" }
            }
            custom_tooltip = to_mod_{{ mod['mod_id'] }}_name_tt
        }
        {%- endfor %}
        
        ##############
        
        if = {
            limit = {
                OR = {
                    {%- for mod in compatible_mods %}
                    is_mod_active = "{{ mod['name'] }}"
                    {%- endfor %}
                    {%- for mod in incompatible_mods %}
                    {%- if "compatibility_patch" in mod %}
                    AND = {
                        is_mod_active = "{{ mod['name'] }}"
                        is_mod_active = "{{ mod['compatibility_patch']['name'] }}"
                    }
                    {%- endif %}
                    {%- endfor %}
                }
            }
            custom_tooltip = to_compatible_mods_active_tt
            {%- for mod in compatible_mods %}
            if = {
                limit = {
                    is_mod_active = "{{ mod['name'] }}"
                }
                custom_tooltip = to_mod_{{ mod['mod_id'] }}_name_tt
            }
            {%- endfor %}
            {%- for mod in incompatible_mods %}
            {%- if "compatibility_patch" in mod %}
            if = {
                limit = {
                    is_mod_active = "{{ mod['name'] }}"
                    is_mod_active = "{{ mod['compatibility_patch']['name'] }}"
                }
                custom_tooltip = to_mod_{mod['mod_id']}_compatibility_tt
            }
            {%- endif %}
            {%- endfor %}
        }
    }
    
    option = {
        name = to_compatibility_check.1.b
        custom_tooltip = to_only_show_incompatibility_on_differences_tt
        set_global_flag = to_only_show_incompatibility_on_differences
    }
}
''')

with open(output_file_events, "w") as file_events:
    file_events.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    file_events.write(template.render(incompatible_mods=incompatible_mods, compatible_mods=compatible_mods))
