trade_goods = [
    {"name": "grain", "fontsize": "small", "offset": -2, "circle_resize": 26},
    {"name": "wine", "fontsize": "small", "offset": -2, "count_offset": 11},
    {"name": "wool", "fontsize": "small", "offset": -2, "count_offset": 11},
    {"name": "cloth", "fontsize": "small", "offset": -2, "no_circle_icon": True},
    {"name": "fish", "fontsize": "small", "offset": -2},
    {"name": "fur", "fontsize": "small", "offset": -2},
    {"name": "salt", "fontsize": "small", "offset": -2, "count_offset": 6},
    {"name": "naval_supplies", "fontsize": "small", "offset": -2, "count_offset": 8},
    {"name": "copper", "fontsize": "normal", "offset": -2},
    {"name": "gold", "fontsize": "normal", "offset": -2},
    {"name": "iron", "fontsize": "normal", "offset": -2, "count_offset": 12},
    {"name": "slaves", "fontsize": "small", "offset": -2, "no_circle_icon": True, "count_offset": 12},
    {"name": "ivory", "fontsize": "small", "offset": -2, "count_offset": 10},
    {"name": "tea", "fontsize": "small", "offset": -2, "count_offset": 16},
    {"name": "chinaware", "fontsize": "small", "offset": -2},
    {"name": "spices", "fontsize": "small", "offset": -2, "count_offset": 6},
    {"name": "coffee", "fontsize": "small", "offset": -2},
    {"name": "cotton", "fontsize": "small", "offset": -2},
    {"name": "sugar", "fontsize": "small", "offset": -2, "count_offset": 16},
    {"name": "tobacco", "fontsize": "small", "offset": -2, "count_offset": 7},
    {"name": "cocoa", "fontsize": "small", "offset": -2},
    {"name": "silk", "fontsize": "small", "offset": -2, "no_circle_icon": True, "count_offset": 9},
    {"name": "dyes", "fontsize": "small", "offset": -2},
    {"name": "tropical_wood", "fontsize": "small", "offset": -2, "count_offset": 13},
    {"name": "livestock", "fontsize": "small", "offset": -2, "count_offset": 13},
    {"name": "incense", "fontsize": "small", "offset": -2},
    {"name": "glass", "fontsize": "small", "offset": -2, "no_circle_icon": True},
    {"name": "paper", "fontsize": "small", "offset": -2, "no_circle_icon": True, "count_offset": 11},
    {"name": "gems", "fontsize": "small", "offset": -2},
    {"name": "coal", "fontsize": "small", "offset": -2, "no_circle_icon": True},
    {"name": "cloves", "fontsize": "small", "offset": -2, "no_circle_icon": True},
    {"name": "unknown", "fontsize": "small", "offset": -2, "no_bonus": True, "no_circle_icon": True},
    {"name": "elysian_silk", "fontsize": "small", "offset": -2, "no_circle_icon": True},
    {"name": "norse_mead", "fontsize": "small", "offset": -2, "no_bonus": True, "no_circle_icon": True},
    {"name": "coal_2", "loc": "Coal", "no_icon": True, "no_circle_icon": True},
    {"name": "skoros_silk", "fontsize": "small", "offset": -2, "no_bonus": True, "no_circle_icon": True},
    {"name": "nothing", "fontsize": "small", "offset": -2, "no_bonus": True, "no_circle_icon": True},
]
