import os

output_file_loc = "o_localisation.txt"

with open(output_file_loc, "w") as output_file_loc:
    output_file_loc.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    for n in range(0, 101):
        output_file_loc.write(f" to_{n}_tt:0 \"{n}\"\n")
    for n in range(0, 51):
        output_file_loc.write(f" to_{n}_plus_red_percentage_tt:0 \"§R+{n}%§!\"\n")
    for n in range(0, 21):
        output_file_loc.write(f" to_{n}_minus_green_percentage_tt:0 \"§G-{n}%§!\"\n")