-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NCountry.ALLOW_ZERO_BASE_VALUES = 1
NDefines.NAI.DEBASE_THRESHOLD = 0
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_COOLDOWN_DURATION = 9999999
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0
NDefines.NCountry.PILLAGE_CAPITAL_DEVELOPMENT_DECREASE = 0
NDefines.NCountry.PILLAGE_CAPITAL_MAX_DEV_PILLAGED = 0
NDefines.NDiplomacy.PEACE_COST_PILLAGE_CAPITAL = 0
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.05
NDefines.NMilitary.UNIT_TYPE_CHANGE_MAX_MORALE = 4.0  -- So that we can switch to greek firethrowers without losing morale