import os

MAX_DEV = 500
DEV_STEP = 50

SHIP_COST_MOD = 0.30
ARTILLERY_MAIN_MOD = 0.10

output_file_cm = "o_conditional_modifiers.txt"
output_file_upgrade_effect = "o_upgrade_effects.txt"
output_file_localisation = "o_localisation.txt"

with open(output_file_cm, 'w') as f:
    f.write(f"\t\t# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    for dev in range(DEV_STEP, MAX_DEV + 1, DEV_STEP):
        perc = dev / MAX_DEV
        ship_cost = round(perc * SHIP_COST_MOD, 2)
        arty_maintenance = round(perc * ARTILLERY_MAIN_MOD, 2)
        f.write("\t\tconditional_modifier = {\n")
        f.write("\t\t\ttooltip_potential = { always = no }\n")
        f.write("\t\t\ttrigger = {\n")
        f.write(f"\t\t\t\tto_owner_has_development_in_province_with_wharf = {{ VALUE = {dev} }}\n")
        f.write("\t\t\t}\n")
        if dev != MAX_DEV:
            f.write(f"\t\t\tmodifier = {{ global_ship_cost = -{ship_cost} artillery_cost = -{arty_maintenance} }}\n")
        else:
            f.write(f"\t\t\tmodifier = {{\n"
                    f"\t\t\t\tglobal_ship_cost = -{ship_cost}\n"
                    f"\t\t\t\tartillery_cost = -{arty_maintenance}\n"
                    f"\t\t\t\tnumber_of_cannons_modifier = 0.1\n"
                    f"\t\t\t\tmax_flagships = 1\n"
                    f"\t\t\t}}\n")
        f.write("\t\t}\n")
        f.write("\n")

with open(output_file_upgrade_effect, 'w') as f:
    f.write(f"\t# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    for i, dev in enumerate(range(MAX_DEV, -1, -DEV_STEP)):
        perc = dev / MAX_DEV
        ship_cost = round(perc * SHIP_COST_MOD, 2)
        arty_maintenance = round(perc * ARTILLERY_MAIN_MOD, 2)
        if i == 0:
            f.write("\tif = {\n")
        elif dev != 0:
            f.write("\telse_if = {\n")
        else:
            f.write("\telse = {\n")
        if dev != 0:
            f.write("\t\tlimit = {\n")
            f.write(f"\t\t\tto_owner_has_development_in_province_with_wharf = {{ VALUE = {dev} }}\n")
            f.write("\t\t}\n")
        f.write(f"\t\tcustom_tooltip = to_arsenal_power_effect_{dev}_tt\n")
        f.write("\t}\n")

with open(output_file_localisation, 'w') as f:
    f.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    for dev in range(0, MAX_DEV + 1, DEV_STEP):
        perc = dev / MAX_DEV
        ship_cost = round(perc * SHIP_COST_MOD, 2)
        arty_maintenance = round(perc * ARTILLERY_MAIN_MOD, 2)
        color = "G"
        if dev == 0:
            color = "Y"
        f.write(f" to_arsenal_power_effect_{dev}_tt:0 \"\\n"
                f"Ship Cost: §{color}-{100 * ship_cost:.1f}%§! from §YArsenal Efficiency§!\\n"
                f"Artillery Cost: §{color}-{100 * arty_maintenance:.1f}%§! from §YArsenal Efficiency§!")
        if dev == MAX_DEV:
            f.write(f"\\nShip Cannons §G+10.0%§! from §YArsenal Efficiency§!"
                    f"[AdditionalFlagshipFromArsenal]")
        f.write(f"\"\n")
