import os

from jinja2 import Template
from exarchs import exarchs

output_file = "o_exarch_extra_merchant_output.txt"

template = Template('''OR = {
{%- for exarch in exarchs %}
    AND = {
        tag = {{ exarch['tag'] }}
        NOT = {
            any_province = {
                nhs_{{ exarch['tag'] }}_province = yes
                NOT = { owned_by = {{ exarch['tag'] }} }
            }
        }
    }
{%- endfor %}
}
''')

f = open(output_file, "w")
f.write(template.render(exarchs=exarchs))
f.close()

output_file = "o_exarch_name_from_province.txt"

f = open(output_file, "w", encoding="utf-8")
f.write(f"	# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
for exarch in exarchs:
    f.write(f"	text = {{\n"
            f"		localisation_key = {exarch['tag']}\n"
            f"		trigger = {{ nhs_{exarch['tag']}_province = yes }}\n"
            f"	}}\n")
f.close()

output_file = "o_scripted_effects.txt"
f = open(output_file, "w", encoding="utf-8")
f.write("to_exarch_effect = {\n")
f.write(f"	# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
for exarch in exarchs:
    f.write(f"	if = {{\n"
            f"		limit = {{ exists = {exarch['tag']} }}\n"
            f"		{exarch['tag']} = {{ $EFFECT$ }}\n"
            f"	}}\n")
f.write("}\n\n")

f.write("to_exarch_effect_from_province = {\n")
f.write(f"	# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
for i in range(len(exarchs)):
    exarch = exarchs[i]
    if i == 0:
        f.write(f"	if = {{\n")
    else:
        f.write(f"	else_if = {{\n")
    f.write(f"		limit = {{ nhs_{exarch['tag']}_province = yes }}\n"
            f"		{exarch['tag']} = {{ $EFFECT$ }}\n"
            f"	}}\n")
f.write("}")
f.close()

output_file = "o_scripted_triggers.txt"
f = open(output_file, "w", encoding="utf-8")

f.write("to_potential_exarch_province = {\n")
f.write(f"	# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
f.write(f"	OR = {{\n")
for exarch in exarchs:
    f.write(f"		nhs_{exarch['tag']}_province = yes\n")
f.write(f"  }}\n")
f.write("}\n\n")

f.write("nhs_exarch_land = {\n")
f.write(f"	# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
f.write(f"	OR = {{\n")
for exarch in exarchs:
    f.write(f"		AND = {{\n"
            f"			$SCOPE$ = {{ tag = {exarch['tag']} }}\n"
            f"			nhs_{exarch['tag']}_province = yes\n"
            f"		}}\n")
f.write(f"	}}\n")
f.write("}\n\n")

f.close()