l_english:
 trade_protectorate_desc:1 "Trade Protectorates transfer §Y50%§! of their trade power to their overlord in exchange for military protection. They gain §G+15.0%§! Goods Produced Modifier, §G+20.0%§! Production Efficiency and §G+25.0%§! Institution Spread, and §G-10%§! Technology Cost in any category the overlord is ahead in.\nThe overlord can call a trade protectorate into their own war in exchange for an opinion penalty.\n§YTrade Protectorates can NOT be diplomatically annexed.§!"
 call_trade_protectorate_into_wars:0 "Call Protectorate to War"
 call_trade_protectorate_into_wars_title:0 "Call Protectorate to War"
 mng_insight_36_tt:1 "\n§GEvent Insight§!:\nThis event will grant us access to more provinces with precious metals as well as a Treasurer advisor with a significant discount."

 ability_devshirme_mechanic:0 "Devshirme"
 ability_land_of_the_christian_sun_mechanic:0 "Land of the Christian Sun"
 ability_system_of_councils_mechanic:0 "System of Councils"
 ability_russian_modernization_mechanic:0 "Modernization"
 ability_perfectionism_mechanic:0 "Perfectionism"