l_english:
 iroquoian_federation_ideas:0 "Haudenosaunee Federation Ideas"
 iroquoian_federation_ideas_start:0 "Haudenosaunee Traditions"
 iroquoian_federation_ideas_bonus:0 "Haudenosaunee Ambitions"
 