l_english:
 PROV151:0 "Konstantinoupolis"
 PROV806:0 "Pisca"
 PROV868:0 "Tongva"
 PROV1001:1 "Missisage"
 PROV1483:0 "Helluland Coast"
 PROV1484:0 "Búrisvágr"
 PROV1485:0 "Thorfinn Straits"
 PROV1486:0 "Njörðr Bay"
 PROV1487:0 "Western Thorfinn Bay"
 PROV1488:0 "Eastern Thorfinn Bay"
 PROV1489:0 "Ísgrunnsævi"
 PROV1490:0 "Eiriksson Gulf"
 PROV1491:0 "Ránarvegr"
 PROV1492:0 "Hefringarvík"
 PROV1493:0 "Dröfnarsund"
 PROV1494:0 "Southern Markland Coast"
 PROV1495:0 "Eastern Markland Coast"
 PROV1496:0 "Vinland Sea"
 
 PROV1499:0 "Massachusetts Bay"
 PROV1500:0 "Delaware Bay"
 PROV1501:0 "Cape Hatteras"
 PROV1502:0 "Sea Islands"
 PROV1503:0 "Bachame Banks"
 PROV1504:1 "Western Sargasso Sea"
 PROV1505:0 "Southern Straits"
 PROV1506:0 "Anthiran Bay"
 PROV1507:0 "Mobile Bay"
 PROV1508:0 "Galveston Bay"
 PROV1509:0 "Tampico Bay"
 PROV1510:0 "Bay of Campeche"
 PROV1511:0 "Lakonian Gulf"
 PROV1512:0 "Yucatan Channel"
 PROV1513:1 "Gulf of Honduras"
 PROV1516:0 "Achillean Channel"
 PROV1517:0 "Central Kyklades"
 PROV1518:0 "Western Kyklades"
 PROV1521:0 "Eastern Kyklades"
 PROV1524:0 "Kaikos Sea"
 PROV1525:0 "Bachame Channel"
 
 PROV1570:0 "Elysian Seamounts"
  
 PROV1659:0 "Skinandivatn"
 PROV1660:0 "Makriá Ourá"
 PROV1661:0 "Káregnóndí"
 PROV1662:0 "Megali Limni"
 PROV1663:0 "Lake Vimur"
  
 PROV1668:1 "Northwestern Eirenic"
 PROV1672:0 "Western Eirenic"
 PROV1675:1 "North Eirenic Equatorial Current"
 PROV1686:0 "Eastern North Eirenic Drift"
 PROV1689:0 "North Eirenic Drift"
 PROV1690:0 "Western North Eirenic Drift"
 PROV1699:0 "Central Eirenic Basin"
 PROV1711:1 "East Eirenic Rise"
 PROV1712:0 "South Equatorial Eirenic Current"
 PROV1714:1 "North Eirenic Converge Zone"
 PROV1715:0 "Eastern Equatorial Eirenic Current"
 PROV1719:0 "South Eirenic Raging Fifties"
 PROV1721:0 "South Eirenic Roaring Forties"
 PROV1724:1 "Southeast Eirenic"
 PROV1729:1 "South Eirenic"
 PROV1730:0 "East Eirenic Ridge"
 PROV1736:0 "Western Equatorial Eirenic Counter Current"
 PROV1740:1 "Equatorial Eirenic Counter Current"
 
 PROV1807:0 "Búri"
 PROV2518:0 "Shaugawaumikong"
 PROV2671:0 "Wemitigoj-Sibi"
 
 PROV2479:0 "Nisenan"
 PROV2608:0 "Atlas Mountains"
 PROV5360:0 "Ymir's Bones"
 PROV5361:0 "Lower Eiriksson River"
 PROV5362:0 "Upper Eiriksson River"
 PROV5363:0 "Patwin"
 PROV5364:0 "Chochenyo"
 PROV5365:0 "Maidu"
 PROV5366:0 "Toulumne"
 PROV5367:0 "Chumash"
 PROV5368:0 "Mono"
 PROV5369:0 "Siskiyou"
 PROV5370:0 "Jaroujiji"
 PROV5371:0 "Waika"
 PROV5372:0 "Yampahpa"
 PROV5373:0 "Shawpatina"
 PROV5374:0 "Tuwanda"
 PROV5375:0 "Great Basin"
 PROV5376:0 "Miwok Bay"
 PROV5377:0 "Chesapeake Bay"
 PROV5378:0 "Kainawa"
 PROV5379:0 "Nitaniksi"
 PROV5380:0 "Sihiykwi"
 PROV5381:0 "Ayokaawa"
 PROV5382:0 "Quitsen"
 PROV5383:0 "Saappeh"
 PROV5384:0 "Naaldlooshii"
 PROV5385:0 "Shana"
 PROV5386:0 "Tillicum"
 PROV5387:0 "Chunut"
 PROV5388:0 "Panamunt"
 PROV5389:0 "Inesen"
 PROV5390:0 "Clatsop"
 PROV5391:0 "Chiluktkwa"
 PROV5392:0 "Nomlaki"
 PROV5393:0 "Kashaya"
 PROV5394:0 "Serrano"
 PROV5395:0 "Tillamook"
 PROV5396:0 "Wetsuweten"
 PROV5397:0 "Dene-thah"
 PROV5398:0 "Gitxsan"
 PROV5399:0 "Tahltan"
 PROV5400:0 "Uinta"
 PROV5401:0 "Ute"
 PROV5402:0 "Daa'bu"
 PROV5403:0 "Muupuchi"
 PROV5404:0 "Quchu"
 PROV5405:0 "Duhubite"
 PROV5406:0 "Puyallup"
 PROV5407:0 "Chelan"
 PROV5408:0 "Quinault"
 PROV5409:0 "Stlatlminc"
 PROV5410:0 "Taitnapam"
 PROV5411:0 "Sammammish"
 PROV5412:0 "Washo"
 PROV5413:0 "Tubatulabal"
 PROV5414:0 "Kawaisu"
 PROV5415:0 "Hastiin"
 PROV5416:0 "Tsekooh"
 PROV5417:0 "Laa'ii"
 PROV5418:0 "Diiya"

 PROV4155:0 "North Carpathians"
 PROV5356:0 "South Carpathians"
 PROV5357:0 "Great Sand Sea"
 PROV5358:0 "Fezzan Desert"
 PROV5359:0 "North Sahara"
 
 PROV1649:0 "Ukerewe"
 PROV4135:0 "Lake Mwitanzige"