l_english:
 dlc_or_feudalism_tooltip:1 "Has Reformed Religion or adopted Legalism."
 CHANGE_DEITY_EFFECT:1 "Change Deity to $NAME|Y$:\n$MODIFIER$"
 ADD_RULER_PERSONALITY:0 "$NAME$ is now known as $PERSONALITY|Y$.\n"
 REMOVE_RULER_PERSONALITY:0 "$NAME$ is no longer known as $PERSONALITY|Y$.\n"

 HRE_INHERITABLE_ENABLED:1 "HRE is now always inherited by the same country.\nSubject princes no longer occupy Emperor's diplomatic relations slots.\n"
 HRE_INHERITABLE_DISABLED:1 "HRE is now open to election!\nEmperor's subject princes will use diplomatic relations slots.\n"

 INCREASE_DISASTER_PROGRESS_EFFECT:0 "§Y$DISASTER$§! progress increases by §R$VALUE$§!"
 DECREASE_DISASTER_PROGRESS_EFFECT:0 "§Y$DISASTER$§! progress decreases by §G$VALUE$§!"

 OWNS_ALL_PROVINCES:0 "Owns or subject owns all provinces:\n"