import json
import os

gui_file = open("TO_achievements.txt", "w")
loc_file = open("to_achievement_localisation.txt", "w")
interface_file = open("to_achievement_interface.txt", "w")

window_gui = """custom_window = {
\tname = to_achievement_window
\tpotential = {
\t\tto_achievement_window_visible = yes
\t}
}

custom_window = {
\tname = to_achievement_window_elysia
\tpotential = {
\t\tto_achievement_window_elysia_visible = yes
\t}
}

"""

window_interface = """\t\twindowType = {
\t\t\tname = "to_achievement_window"
\t\t\tposition = { x = 0 y = 0 }
\t\t\tOrientation = "CENTER"
\t\t\tscripted = yes
    
\t\t\twindowType = {
\t\t\t\tname = "to_achievement_window"
\t\t\t\tposition = { x = 0 y = 0 }
\t\t\t\tOrientation = "CENTER"
\t\t\t\tscripted = yes

"""

y_spacing = 100
x_spacing = 383
top_margin = 115
left_margin = 15

status_offset_x = 310
status_offset_y = 32

title_offset_x = 160
title_offset_y = 12
title_width = 185
title_font = "vic_22"

description_offset_x = 160
description_offset_y = 20
description_width = 185
description_font = "vic_18"

with open("achievement_definitions.json") as file:
    data = json.load(file)
    loc_file.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    gui_file.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    gui_file.write(window_gui)
    interface_file.write(f"\t\t# Third Odyssey\n")
    interface_file.write(f"\t\t# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    interface_file.write(window_interface)

    for i, entry in enumerate(data):
        gui_file.write(f"custom_icon = {{\n"
                       f"\tname = to_achievement_{entry["name"]}_icon\n"
                       f"}}\n\n")
        gui_file.write(f"custom_icon = {{\n"
                       f"\tname = to_achievement_{entry["name"]}_background\n"
                       f"}}\n\n")
        gui_file.write(f"custom_text_box = {{\n"
                       f"\tname = to_achievement_{entry["name"]}_title\n"
                       f"}}\n\n")
        gui_file.write(f"custom_text_box = {{\n"
                       f"\tname = to_achievement_{entry["name"]}_description\n"
                       f"}}\n\n")
        gui_file.write(f"custom_icon = {{\n"
                       f"\tname = to_achievement_{entry["name"]}_status\n"
                       f"\tframe = {{\n"
                       f"\t\tnumber = 1\n"
                       f"\t\ttrigger = {{ to_achievement_{entry["name"]}_status_complete = yes }}\n"
                       f"\t}}\n"
                       f"\tframe = {{\n"
                       f"\t\tnumber = 2\n"
                       f"\t\ttrigger = {{ to_achievement_{entry["name"]}_status_failed = yes }}\n"
                       f"\t}}\n"
                       f"\tframe = {{\n"
                       f"\t\tnumber = 3\n"
                       f"\t\ttrigger = {{}}\n"
                       f"\t}}\n"
                       f"}}\n\n")

        loc_file.write(f" to_achievement_{entry["name"]}_title:0 \"{entry["title"]}\"\n"
                       f" to_achievement_{entry["name"]}_description:0 \"{entry["trigger_description"]}\"\n")

        if i % 2 == 0:
            x = left_margin
        else:
            x = left_margin + x_spacing
        y = top_margin + i // 2 * y_spacing

        indentation1 = "\t\t\t\t"
        indentation2 = "\t\t\t\t\t"

        interface_file.write(f"{indentation1}iconType = {{\n"
                             f"{indentation2}name = \"to_achievement_{entry["name"]}_icon\"\n"
                             f"{indentation2}position = {{ x = {x} y = {y} }}\n"
                             f"{indentation2}quadTextureSprite = \"GFX_to_achievement_{entry["name"]}_icon\"\n"
                             f"{indentation2}scripted = yes\n"
                             f"{indentation1}}}\n\n")

        interface_file.write(f"{indentation1}iconType = {{\n"
                             f"{indentation2}name = \"to_achievement_{entry["name"]}_background\"\n"
                             f"{indentation2}position = {{ x = {x} y = {y} }}\n"
                             f"{indentation2}quadTextureSprite = \"GFX_to_achievement_entry_{entry["difficulty"]}\"\n"
                             f"{indentation2}scripted = yes\n"
                             f"{indentation1}}}\n\n")

        interface_file.write(f"{indentation1}instantTextBoxType = {{\n"
                             f"{indentation2}name = \"to_achievement_{entry["name"]}_title\"\n"
                             f"{indentation2}position = {{ x = {x + title_offset_x} y = {y + title_offset_y} }}\n"
                             f"{indentation2}font = \"{title_font}\"\n"
                             f"{indentation2}maxWidth = {title_width}\n"
                             f"{indentation2}maxHeight = 22\n"
                             f"{indentation2}fixedsize = yes\n"
                             f"{indentation2}scripted = yes\n"
                             f"{indentation1}}}\n\n")

        interface_file.write(f"{indentation1}instantTextBoxType = {{\n"
                             f"{indentation2}name = \"to_achievement_{entry["name"]}_description\"\n"
                             f"{indentation2}position = {{ x = {x + description_offset_x} y = {y + description_offset_y} }}\n"
                             f"{indentation2}font = \"{description_font}\"\n"
                             f"{indentation2}maxWidth = {description_width}\n"
                             f"{indentation2}maxHeight = 22\n"
                             f"{indentation2}fixedsize = yes\n"
                             f"{indentation2}scripted = yes\n"
                             f"{indentation1}}}\n\n")

        interface_file.write(f"{indentation1}iconType = {{\n"
                             f"{indentation2}name = \"to_achievement_{entry["name"]}_status\"\n"
                             f"{indentation2}position = {{ x = {x + status_offset_x} y = {y + status_offset_y} }}\n"
                             f"{indentation2}quadTextureSprite = \"GFX_to_achievement_status_icons\"\n"
                             f"{indentation2}scripted = yes\n"
                             f"{indentation1}}}\n\n")
    interface_file.write("\t\t\t}\n")
    interface_file.write("\t\t}\n")

gui_file.close()
loc_file.close()
interface_file.close()
