import os

output_file_cl = "o_customizable_localisation.txt"
output_file_loc = "o_localisation.txt"

buildings = [
    ("temple", "[Root.GetTempleNamePlural]", 1),
    ("cathedral", "[Root.GetCathedralNamePlural]", 2),

    ("workshop", "Workshops", 1),
    ("counting_house", "Counting Houses", 2),

    ("marketplace", "Marketplaces", 1),
    ("trade_depot", "Trade Depots", 2),
    ("stock_exchange", "Stock Exchanges", 3),

    ("barracks", "Barracks", 1),
    ("training_fields", "Training Fields", 2),

    ("regimental_camp", "Regimental Camps", 1),
    ("conscription_center", "Conscription Centers", 2),

    ("dock", "Docks", 1),
    ("drydock", "Drydocks", 2),

    ("shipyard", "Shipyards", 1),
    ("grand_shipyard", "Grand Shipyards", 2),

    ("courthouse", "Courthouses", 1),
    ("town_hall", "Town Houses", 2),

    ("university", "Universities", 2),

    ("fort_15th", "Castles", 1),
    ("fort_16th", "Bastions", 2),
    ("fort_17th", "Star Forts", 3),
    ("fort_18th", "Fortresses", 4),

    ("coastal_defence", "Coastal Defences", 1),
    ("naval_battery", "Naval Batteries", 2),

    ("manufactory", "Manufacturies", 2),

    ("ramparts", "Ramparts", 2),
    ("soldier_households", "Soldier Households", 2),
    ("impressment_offices", "Impressment Offices", 2),
    ("state_house", "State Houses", 2),
]

with open(output_file_cl, "w") as file:
    file.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")
    for tag, _, _ in buildings:
        file.write(f"defined_text = {{\n"
                   f"\tname = ElysiumBuildingCounter_{tag}\n"
                   f"\ttext = {{\n"
                   f"\t\tlocalisation_key = ZERO\n"
                   f"\t\ttrigger = {{\n"
                   f"\t\t\tis_variable_equal = {{ which = to_ElysiumBuildingCount_{tag} value = 0 }}\n"
                   f"\t\t}}\n"
                   f"\t}}\n"
                   f"\ttext = {{\n"
                   f"\t\tlocalisation_key = to_{tag}_elysium_counter_tt\n"
                   f"\t}}\n"
                   f"}}\n")

with open(output_file_loc, "w") as file:
    file.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")

    file.write(f" to_ElysiumBuildingCount_trigger_tt:0 \"Owns §Y600§! buildings on the continent of §YElysium§!."
               f"\\n§YAdvanced buildings§!, §Yuniversities§! and §Ymanufactories§! count as multiple buildings."
               f"\\n--------------\\nCurrent status: §Y[GetElysiumBuildingCount]§!\\n--------------")
    index = 0
    for tag, name, value in buildings:
        file.write(f"\\n")
        # if index % 2 == 0:
        #     file.write(f"\\n")
        # else:
        #     file.write(f"      ")
        file.write(f"{name}: §Y[ElysiumBuildingCounter_{tag}]§!")
        if value > 1:
            file.write(f" (§Yx{value}§!)")
        index += 1

    file.write(f"\"\n")
    for tag, _, value in buildings:
        file.write(f" to_{tag}_elysium_counter_tt:0 \"[Root.to_ElysiumBuildingCount_{tag}.GetValue]\"\n")
