from jinja2 import Template
from roads import roads

output_file_LOC = "localisation_mission_checks.txt"
output_file_CL = "customizable_localisation_mission_checks.txt"

templateCL = Template('''{%- for road in roads %}
{%- for province in road["provinces"] %}
{%- if "duplicate" not in province %}
defined_text = {
	name = OwnsOrAllyOwns_{{ province["id"] }}
	random = no
	text = {
		localisation_key = to_nat_y_icon_tt
		trigger = {
			{{ province["id"] }} = { country_or_subject_or_ally_or_ally_subject_holds = { TAG = ROOT } }
		}
	}

	text = {
		localisation_key = to_nat_x_icon_tt
	}
}
{%- endif %}
{% endfor %}
{%- endfor %}
''')

f = open(output_file_CL, "w")
f.write("# Code generated by elysian_highways_mission_checks.py\n")
f.write(templateCL.render(roads=roads))
f.close()

f = open(output_file_LOC, "w", encoding='cp1250')
for road in roads:
    f.write(f' {road["trigger_name"]}_tt:0 "The following provinces are owned by §Y[Root.GetName]§! or its Allies, '
            f'their subjects, or the subjects of their subjects:')
    for province in road["provinces"]:
        f.write(f'\\n   [Root.OwnsOrAllyOwns_{province["id"]}]§Y[{province["id"]}.GetName]§!')
    f.write('\"\n')
f.close()
