from jinja2 import Template

output_file_LOC = "localisation.txt"
output_file_CL = "customizable_localisation.txt"

roads = [
    {
        "name": "to_owns_elysian_highway_north",
        "provinces": [
            {"id": 2551},
            {"id": 2555},
            {"id": 948},
            {"id": 2525},
            {"id": 2526},
            {"id": 940},
            {"id": 4921},
            {"id": 2520},
            {"id": 4904},
        ]
    },
    {
        "name": "to_owns_elysian_highway_south",
        "provinces": [
            {"id": 935},
            {"id": 2527},
            {"id": 2531},
            {"id": 4883},
            {"id": 918},
            {"id": 939},
            {"id": 4887},
            {"id": 2520, "duplicate": True},
            {"id": 4904, "duplicate": True},
        ]
    }
]

templateCL = Template('''{%- for road in roads %}
{%- for province in road["provinces"] %}
{%- if "duplicate" not in province %}
defined_text = {
	name = OwnsOrAllyOwns_{{ province["id"] }}
	random = no
	text = {
		localisation_key = to_nat_y_icon_tt
		trigger = {
			{{ province["id"] }} = { country_or_subject_or_ally_or_ally_subject_holds = { TAG = ROOT } }
		}
	}

	text = {
		localisation_key = to_nat_x_icon_tt
	}
}
{%- endif %}
{% endfor %}
{%- endfor %}
''')

f = open(output_file_CL, "w")
f.write("# Code generated by cahokian_roads.py\n")
f.write(templateCL.render(roads=roads))
f.close()

f = open(output_file_LOC, "w")
for road in roads:
    f.write(f' {road["name"]}_tt:0 "The following provinces are owned by §Y[Root.GetName]§! or its Allies, '
            f'their subjects, or the subjects of their subjects:')
    for province in road["provinces"]:
        f.write(f'\\n   [Root.OwnsOrAllyOwns_{province["id"]}]§Y[{province["id"]}.GetName]§!')
    f.write('\"\n')
f.close()
