from jinja2 import Template
from roads import roads

output_file = "road_checks.txt"
output_file_road_lists = "road_lists.txt"

template = Template('''{%- for road in roads %}
to_elysian_highway_{{ road["name"] }}_effect = {
    # Code generated by elysian_highways_road_check.py
{%- for province in road["provinces"] %}
    if = {
        limit = {
            {{ province["id"] }} = { $PROVINCE_TRIGGER$ = yes }
        }
        {{ province["id"] }} = { $PROVINCE_EFFECT$ = yes }
    }
{%- endfor %}
}
{%- endfor %}
''')

f = open(output_file, "w")
f.write(template.render(roads=roads))
f.close()

f = open(output_file_road_lists, "w")
for road in roads:
    f.write(f' to_elysian_highway_{road["name"]}_provinces_tt:0 \"')
    for province in road["provinces"][:-1]:
        f.write(f'[{province["id"]}.GetName], ')
    f.write(f'[{road["provinces"][-1]["id"]}.GetName]\"\n')
f.close()