import os

MUSIC_FOLDER = "../../../submods/TO_music/music"
ASSET_FILE = "TO_music.asset"

f = open(os.path.join(MUSIC_FOLDER, ASSET_FILE), "w")
f.write(f"# Code generated by {os.path.basename(os.getcwd())}/{os.path.basename(__file__)}\n")

for file in os.listdir(MUSIC_FOLDER):
    filename = os.fsdecode(file)
    if not filename.endswith(".ogg"):
        continue
    correct_filename = filename.replace(" ", "_").replace("'", "").replace(",", "")
    os.rename(os.path.join(MUSIC_FOLDER, filename), os.path.join(MUSIC_FOLDER, correct_filename))
    f.write(f"music = {{\n\tname = {os.path.splitext(correct_filename)[0]}\n\tfile = {correct_filename}\n}}\n")

f.close()